// Registry of prebuilt Donor CRM report definitions surfaced by the Reports app.

import type { ReportCategory, ReportDefinition } from "@/app/components/reports-app/report-types";

export const REPORT_CATEGORIES: ReportCategory[] = [
  { id: "all", label: "All Reports", description: "Every prebuilt and custom report available in Oyama Reports." },
  { id: "donations", label: "Donations", description: "Gift detail, designation, receipt, and reconciliation reports." },
  { id: "donor-reports", label: "Donor Reports", description: "Constituent, household, organization, and stewardship rollups." },
  { id: "giving-trends", label: "Giving Trends", description: "Monthly, yearly, and board-ready fundraising trends." },
  { id: "receipts-letters", label: "Receipts & Letters", description: "Receipt, label, letter list, and acknowledgment reports." },
  { id: "campaigns", label: "Campaigns", description: "Campaign performance, appeals, goals, and designation outcomes." },
  { id: "events", label: "Events", description: "Scoped event donations, gala donors, registrations, and follow-up." },
  { id: "follow-up", label: "Follow-Up", description: "Open, overdue, and completed stewardship work queues." },
  { id: "monthly-giving", label: "Monthly Giving", description: "Recurring donor health, failed payments, and projected value." },
  { id: "lapsed-donors", label: "Lapsed Donors", description: "LYBUNT, SYBUNT, and reactivation audience reports." },
  { id: "top-donors", label: "Top Donors", description: "Ranked donor lists for recognition and leadership review." },
  { id: "first-time-donors", label: "First-Time Donors", description: "New donor welcome, source, and acknowledgment reports." },
  { id: "households-orgs", label: "Households/Churches/Organizations", description: "Group giving, church, household, and organization reports." },
  { id: "custom-reports", label: "Custom Reports", description: "Saved custom views built from guided templates." },
];

export const REPORT_DEFINITIONS: ReportDefinition[] = [
  {
    id: "donations-detail",
    title: "Donations Report",
    purpose: "Detailed list of donors and donations based on date, fund, payment, campaign, and donor filters.",
    categoryId: "donations",
    sourceModule: "Donor CRM",
    outputs: ["Dashboard", "Data Grid", "CSV", "PDF", "Letter List"],
    status: "Working",
    lastRun: "May 26, 2026",
    primaryChart: "line",
    endpoint: "/api/reports/recent-donations",
    quickFilters: ["Date range", "Payment type", "Designation", "Campaign", "Church"],
  },
  {
    id: "donations-by-designation",
    title: "Donations by Designation",
    purpose: "Shows where gifts are going across funds, programs, campaigns, and restricted designations.",
    categoryId: "donations",
    sourceModule: "Donor CRM",
    outputs: ["Dashboard", "CSV", "PDF", "Board Summary"],
    status: "Working",
    lastRun: "May 25, 2026",
    primaryChart: "donut",
    endpoint: "/api/reports/payment-breakdown",
    quickFilters: ["Date range", "Designation", "Campaign", "Amount range"],
  },
  {
    id: "monthly-giving-report",
    title: "Monthly Giving Report",
    purpose: "Tracks recurring donors, monthly revenue, projected annual value, and payment health.",
    categoryId: "monthly-giving",
    sourceModule: "Donor CRM",
    outputs: ["Dashboard", "Data Grid", "CSV", "PDF"],
    status: "Working",
    lastRun: "May 24, 2026",
    primaryChart: "line",
    endpoint: "/api/reports/giving-by-month",
    quickFilters: ["Recurring status", "Date range", "Payment type", "Giving capacity"],
  },
  {
    id: "top-donors",
    title: "Top Donors",
    purpose: "Ranks donors by selected giving basis for recognition, stewardship, and portfolio planning.",
    categoryId: "top-donors",
    sourceModule: "Donor CRM",
    outputs: ["Data Grid", "CSV", "PDF", "Board Summary"],
    status: "Working",
    lastRun: "May 23, 2026",
    primaryChart: "bar",
    endpoint: "/api/reports/top-donors",
    quickFilters: ["Date range", "Donor type", "Giving capacity", "Household"],
  },
  {
    id: "first-time-donors",
    title: "First-Time Donors",
    purpose: "Finds new donors, first gift source, acknowledgment status, and welcome follow-up readiness.",
    categoryId: "first-time-donors",
    sourceModule: "Donor CRM",
    outputs: ["Data Grid", "CSV", "Letter List", "PDF"],
    status: "Partial",
    lastRun: "May 22, 2026",
    primaryChart: "bar",
    endpoint: "/api/reports/new-vs-returning",
    quickFilters: ["Date range", "Campaign", "Follow-up status", "Donor tags"],
  },
  {
    id: "lapsed-donor-report",
    title: "Lapsed Donor Report",
    purpose: "Identifies donors who gave previously but have not renewed in the selected reporting window.",
    categoryId: "lapsed-donors",
    sourceModule: "Donor CRM",
    outputs: ["Data Grid", "CSV", "Letter List", "PDF"],
    status: "Working",
    lastRun: "May 21, 2026",
    primaryChart: "bar",
    endpoint: "/api/reports/lybunt",
    quickFilters: ["Date range", "Giving capacity", "Follow-up status", "Donor tags"],
  },
  {
    id: "campaign-performance",
    title: "Campaign Performance",
    purpose: "Compares campaign revenue, donor count, average gift, goal progress, and follow-up queues.",
    categoryId: "campaigns",
    sourceModule: "Donor CRM",
    outputs: ["Dashboard", "CSV", "PDF", "Board Summary"],
    status: "Working",
    lastRun: "May 20, 2026",
    primaryChart: "bar",
    endpoint: "/api/reports/campaign-performance",
    quickFilters: ["Campaign", "Date range", "Designation", "Amount range"],
  },
  {
    id: "year-over-year",
    title: "Year Over Year Giving",
    purpose: "Compares current year giving with prior year by month for board and finance review.",
    categoryId: "giving-trends",
    sourceModule: "Donor CRM",
    outputs: ["Dashboard", "CSV", "PDF", "Board Summary"],
    status: "Working",
    lastRun: "May 19, 2026",
    primaryChart: "stacked-bar",
    endpoint: "/api/reports/year-comparison",
    quickFilters: ["Date range", "Campaign", "Designation", "Donor type"],
  },
  {
    id: "receipts-needed",
    title: "Receipts & Acknowledgments Needed",
    purpose: "Creates receipt, label, and letter lists for donations that still need acknowledgment.",
    categoryId: "receipts-letters",
    sourceModule: "Letters",
    outputs: ["Data Grid", "CSV", "Letter List", "Labels", "PDF"],
    status: "Partial",
    lastRun: "May 18, 2026",
    primaryChart: "bar",
    quickFilters: ["Date range", "Payment type", "Follow-up status", "Designation"],
  },
  {
    id: "event-gala-donors",
    title: "Event and Gala Donors",
    purpose: "Surfaces event donations, registrations, sponsors, and post-event donor follow-up.",
    categoryId: "events",
    sourceModule: "Cross-module",
    outputs: ["Dashboard", "Data Grid", "CSV", "PDF"],
    status: "Partial",
    lastRun: "May 17, 2026",
    primaryChart: "bar",
    quickFilters: ["Event", "Campaign", "Follow-up status", "Donor type"],
  },
  {
    id: "follow-up-workload",
    title: "Follow-Up Workload",
    purpose: "Shows overdue, open, and completed stewardship tasks tied to donors, gifts, campaigns, and events.",
    categoryId: "follow-up",
    sourceModule: "Donor CRM",
    outputs: ["Dashboard", "Data Grid", "CSV"],
    status: "Partial",
    lastRun: "May 16, 2026",
    primaryChart: "bar",
    quickFilters: ["Follow-up status", "Date range", "Campaign", "Donor tags"],
  },
  {
    id: "household-organization-giving",
    title: "Households, Churches, and Organizations",
    purpose: "Aggregates giving by household, church, organization, and linked group records.",
    categoryId: "households-orgs",
    sourceModule: "Donor CRM",
    outputs: ["Data Grid", "CSV", "PDF", "Labels"],
    status: "Partial",
    lastRun: "May 15, 2026",
    primaryChart: "bar",
    quickFilters: ["Church/organization", "Household", "Date range", "Giving capacity"],
  },
  {
    id: "board-summary",
    title: "Board-Ready Fundraising Summary",
    purpose: "A clean presentation view with revenue, retention, first-time donors, lapsed donors, and campaign progress.",
    categoryId: "giving-trends",
    sourceModule: "Donor CRM",
    outputs: ["Dashboard", "PDF", "Board Summary"],
    status: "Working",
    lastRun: "May 14, 2026",
    primaryChart: "line",
    endpoint: "/api/reports/board-summary",
    quickFilters: ["Date range", "Campaign", "Designation", "Donor type"],
  },
  {
    id: "pledge-forecast",
    title: "Pledge Forecast",
    purpose: "Forecasts pledge balances, expected installments, overdue commitments, and campaign impact.",
    categoryId: "donations",
    sourceModule: "Donor CRM",
    outputs: ["Dashboard", "Data Grid", "CSV", "PDF"],
    status: "Coming Soon",
    lastRun: "Not run",
    primaryChart: "line",
    quickFilters: ["Campaign", "Date range", "Amount range", "Follow-up status"],
  },
  {
    id: "custom-builder-starter",
    title: "Custom Report Builder Starter",
    purpose: "Starts a guided custom report from proven templates instead of a blank query screen.",
    categoryId: "custom-reports",
    sourceModule: "Donor CRM",
    outputs: ["Dashboard", "Data Grid", "CSV", "PDF"],
    status: "Partial",
    lastRun: "Not run",
    primaryChart: "none",
    quickFilters: ["Data source", "Fields", "Grouping", "Export format"],
  },
];

export const DEFAULT_REPORT_ID = "donations-detail";
