@echo off
REM Packages a production demo bundle and creates a zip in dist\.
setlocal EnableExtensions EnableDelayedExpansion

for %%I in ("%~dp0..") do set "ROOT=%%~fI"
set "DIST_DIR=%ROOT%\dist"
set "TIMESTAMP="
for /f "delims=" %%T in ('powershell -NoProfile -Command "Get-Date -Format yyyyMMdd-HHmmss"') do set "TIMESTAMP=%%T"
if not defined TIMESTAMP set "TIMESTAMP=19700101-000000"
set "BUNDLE_NAME=oyamacrm-demo-%TIMESTAMP%"
set "STAGE_DIR=%DIST_DIR%\%BUNDLE_NAME%"
set "ZIP_PATH=%DIST_DIR%\%BUNDLE_NAME%.zip"

if not exist "%DIST_DIR%" mkdir "%DIST_DIR%"
if exist "%STAGE_DIR%" rmdir /s /q "%STAGE_DIR%"
mkdir "%STAGE_DIR%"

echo.
echo [1/6] Resolving metadata...
set "APP_VERSION=0.0.0"
for /f "delims=" %%V in ('powershell -NoProfile -Command "(Get-Content '%ROOT%\package.json' | ConvertFrom-Json).version"') do set "APP_VERSION=%%V"
set "BUILD_DATE=1970-01-01"
for /f "delims=" %%D in ('powershell -NoProfile -Command "Get-Date -Format yyyy-MM-dd"') do set "BUILD_DATE=%%D"
set "GIT_COMMIT=local-demo"
for /f "delims=" %%G in ('git -C "%ROOT%" rev-parse --short HEAD 2^>nul') do set "GIT_COMMIT=%%G"

echo [2/6] Copying required directories...
call :copy_dir "app"
call :copy_dir "server"
call :copy_dir "prisma"
call :copy_dir "public"
call :copy_dir "docs"
call :copy_dir "scripts"
call :copy_dir "easy_prep_tools"
if errorlevel 1 goto :fail

echo [3/6] Copying required root files...
call :copy_file ".env.example"
call :copy_file "README.md"
call :copy_file "AGENTS.md"
call :copy_file "CLAUDE.md"
call :copy_file "package.json"
call :copy_file "pnpm-lock.yaml"
call :copy_file "next.config.ts"
call :copy_file "next-env.d.ts"
call :copy_file "postcss.config.mjs"
call :copy_file "eslint.config.mjs"
call :copy_file "ecosystem.config.cjs"
call :copy_file "tsconfig.json"
call :copy_file "vitest.config.mts"
if errorlevel 1 goto :fail

echo [4/6] Generating .env.production in staged bundle...
> "%STAGE_DIR%\.env.production" (
  echo # Production demo environment generated by easy_prep_tools\prepare_production_demo.bat
  echo NODE_ENV=production
  echo API_PORT=4000
  echo NEXT_PUBLIC_API_URL=http://localhost:4000
  echo FRONTEND_ORIGIN=http://localhost:3001
  echo DATABASE_URL=mysql://user:password@localhost:3306/oyamacrm
  echo WATCHDOG_DATABASE_URL=mysql://user:password@localhost:3306/oyama_watchdog
  echo JWT_SECRET=replace-with-a-long-random-secret
  echo JWT_REFRESH_SECRET=replace-with-a-second-long-random-secret
  echo APP_NAME=OyamaCRM
  echo APP_VERSION=%APP_VERSION%
  echo BUILD_DATE=%BUILD_DATE%
  echo GIT_COMMIT=%GIT_COMMIT%
  echo RELEASE_CHANNEL=production-demo
  echo LAST_AUDIT_DATE=%BUILD_DATE%
  echo NEXT_PUBLIC_APP_NAME=OyamaCRM
  echo NEXT_PUBLIC_APP_VERSION=%APP_VERSION%
  echo NEXT_PUBLIC_BUILD_DATE=%BUILD_DATE%
  echo NEXT_PUBLIC_GIT_COMMIT=%GIT_COMMIT%
  echo NEXT_PUBLIC_RELEASE_CHANNEL=production-demo
  echo NEXT_PUBLIC_APP_ENV=production
  echo NEXT_PUBLIC_LAST_AUDIT_DATE=%BUILD_DATE%
)

echo [5/6] Writing quick start helper for demo machines...
> "%STAGE_DIR%\start-demo.bat" (
  echo @echo off
  echo REM Builds and starts the demo locally from this packaged folder.
  echo setlocal
  echo if not exist ".env" copy /Y ".env.production" ".env" ^>nul
  echo call pnpm install --frozen-lockfile
  echo call pnpm db:generate
  echo call pnpm build
  echo call pnpm build:server
  echo start "OyamaCRM API" cmd /c "pnpm start:server"
  echo call pnpm start
)

echo [6/6] Creating zip archive...
if exist "%ZIP_PATH%" del /q "%ZIP_PATH%"
powershell -NoProfile -ExecutionPolicy Bypass -Command "Compress-Archive -Path '%STAGE_DIR%\*' -DestinationPath '%ZIP_PATH%' -Force"
if errorlevel 1 goto :fail

echo.
echo SUCCESS: Bundle ready
echo Folder: "%STAGE_DIR%"
echo Zip:    "%ZIP_PATH%"
goto :eof

:copy_dir
set "SRC=%ROOT%\%~1"
set "DST=%STAGE_DIR%\%~1"
if not exist "%SRC%" (
  echo WARN: Skipping missing directory "%~1"
  goto :eof
)
powershell -NoProfile -ExecutionPolicy Bypass -Command "New-Item -ItemType Directory -Path '%DST%' -Force | Out-Null; Copy-Item -Path '%SRC%\*' -Destination '%DST%' -Recurse -Force -ErrorAction Stop"
if errorlevel 1 (
  echo ERROR: Failed to copy directory "%~1"
  exit /b 1
)
if exist "%DST%\node_modules" rmdir /s /q "%DST%\node_modules"
if exist "%DST%\.next" rmdir /s /q "%DST%\.next"
if exist "%DST%\coverage" rmdir /s /q "%DST%\coverage"
if exist "%DST%\dist" rmdir /s /q "%DST%\dist"
goto :eof

:copy_file
set "SRC=%ROOT%\%~1"
set "DST=%STAGE_DIR%\%~1"
if not exist "%SRC%" (
  echo WARN: Skipping missing file "%~1"
  goto :eof
)
copy /Y "%SRC%" "%DST%" >nul
if errorlevel 1 (
  echo ERROR: Failed to copy file "%~1"
  exit /b 1
)
goto :eof

:fail
echo.
echo FAILED: Could not produce production demo bundle.
exit /b 1
