/** Central permission key registry and role-default policy for fine-grained access control. */
import { ROLE_HIERARCHY, type UserRole } from "../middleware/requireRole.js";

/** All supported fine-grained permission keys. */
export const PERMISSION_KEYS = [
  "view:constituents",
  "edit:constituents",
  "delete:constituents",
  "view:donations",
  "edit:donations",
  "delete:donations",
  "view:campaigns",
  "edit:campaigns",
  "view:reports",
  "view:communications",
  "edit:communications",
  "view:events",
  "edit:events",
  "view:tasks",
  "edit:tasks",
  "import:data",
  "export:data",
  "view:custom_fields",
  "edit:custom_fields",
  "view:audit_logs",
  "watchdog:view_dashboard",
  "watchdog:view_logs",
  "watchdog:vault:read",
  "watchdog:vault:read_secret",
  "watchdog:vault:write",
  "watchdog:vault:delete",
  "watchdog:incident:acknowledge",
  "watchdog:incident:escalate",
  "watchdog:incident:resolve",
  "watchdog:manage",
  "feedback.submit",
  "feedback.view_own",
  "watchdog.tickets.view",
  "watchdog.tickets.manage",
  "watchdog.tickets.assign",
  "watchdog.tickets.resolve",
  "watchdog.tickets.delete",
  "watchdog.view",
  "watchdog.admin",
  "watchdog.backups.view",
  "watchdog.backups.create",
  "watchdog.backups.delete",
  "watchdog.restore.view",
  "watchdog.restore.dry_run",
  "watchdog.restore.execute",
  "watchdog.restore.break_glass",
  "watchdog.vault.view",
  "watchdog.vault.create",
  "watchdog.vault.edit",
  "watchdog.vault.reveal",
  "watchdog.vault.copy",
  "watchdog.vault.rotate",
  "watchdog.security.view",
  "watchdog.audit.view",
  "watchdog.settings.manage",
  "watchdog.health.view",
  "hrm.view",
  "hrm.people.manage",
  "hrm.schedules.manage",
  "hrm.locations.manage",
  "hrm.messages.manage",
  "hrm.settings.manage",
  "grants.view",
  "grants.create",
  "grants.edit",
  "grants.delete",
  "grants.manage_funders",
  "grants.manage_tasks",
  "grants.manage_resources",
  "grants.manage_deadlines",
  "grants.record_decision",
  "grants.link_received_award",
  "steward_paths.view",
  "steward_paths.create",
  "steward_paths.edit",
  "steward_paths.activate",
  "steward_paths.archive",
  "steward_paths.enroll",
  "steward_paths.pause",
  "steward_paths.manage_all",
  "steward_paths.process_due_steps",
  "steward_paths.email_auto_send",
  "letters.view",
  "letters.create",
  "letters.edit",
  "letters.archive",
  "letters.generate",
  "letters.generate_batch",
  "letters.manage_print_queue",
  "letters.manage_mail_queue",
  "letters.manage_signatures",
  "letters.manage_branding",
  "letters.create_email_draft",
  "letters.export_pdf",
  "letters.view_sensitive_merge_data",
  "letters.manage_all",
  "oyama_password.view",
  "oyama_password.create",
  "oyama_password.edit",
  "oyama_password.delete",
  "oyama_password.reveal",
  "oyama_password.share",
  "oyama_password.backup",
  "oyama_password.restore",
] as const;

/** Union type for one permission key. */
export type PermissionKey = (typeof PERMISSION_KEYS)[number];

/** Runtime guard to validate one unknown permission key. */
export function isPermissionKey(value: string): value is PermissionKey {
  return (PERMISSION_KEYS as readonly string[]).includes(value);
}

/** Default role gate for one permission key when no explicit override exists. */
interface PermissionDefault {
  minRole: UserRole;
}

/** Default fallback policy used when a user has no explicit UserPermission row. */
const PERMISSION_DEFAULTS: Record<PermissionKey, PermissionDefault> = {
  "view:constituents": { minRole: "readonly" },
  "edit:constituents": { minRole: "staff" },
  "delete:constituents": { minRole: "admin" },
  "view:donations": { minRole: "readonly" },
  "edit:donations": { minRole: "staff" },
  "delete:donations": { minRole: "admin" },
  "view:campaigns": { minRole: "readonly" },
  "edit:campaigns": { minRole: "staff" },
  "view:reports": { minRole: "shareview_user" },
  "view:communications": { minRole: "readonly" },
  "edit:communications": { minRole: "staff" },
  "view:events": { minRole: "readonly" },
  "edit:events": { minRole: "staff" },
  "view:tasks": { minRole: "readonly" },
  "edit:tasks": { minRole: "staff" },
  "import:data": { minRole: "manager" },
  "export:data": { minRole: "manager" },
  "view:custom_fields": { minRole: "readonly" },
  "edit:custom_fields": { minRole: "manager" },
  "view:audit_logs": { minRole: "manager" },
  "watchdog:view_dashboard": { minRole: "admin" },
  "watchdog:view_logs": { minRole: "admin" },
  "watchdog:vault:read": { minRole: "admin" },
  "watchdog:vault:read_secret": { minRole: "admin" },
  "watchdog:vault:write": { minRole: "admin" },
  "watchdog:vault:delete": { minRole: "admin" },
  "watchdog:incident:acknowledge": { minRole: "admin" },
  "watchdog:incident:escalate": { minRole: "admin" },
  "watchdog:incident:resolve": { minRole: "admin" },
  "watchdog:manage": { minRole: "admin" },
  "feedback.submit": { minRole: "report_viewer" },
  "feedback.view_own": { minRole: "report_viewer" },
  "watchdog.tickets.view": { minRole: "admin" },
  "watchdog.tickets.manage": { minRole: "admin" },
  "watchdog.tickets.assign": { minRole: "admin" },
  "watchdog.tickets.resolve": { minRole: "admin" },
  "watchdog.tickets.delete": { minRole: "admin" },
  "watchdog.view": { minRole: "admin" },
  "watchdog.admin": { minRole: "admin" },
  "watchdog.backups.view": { minRole: "admin" },
  "watchdog.backups.create": { minRole: "admin" },
  "watchdog.backups.delete": { minRole: "admin" },
  "watchdog.restore.view": { minRole: "admin" },
  "watchdog.restore.dry_run": { minRole: "admin" },
  "watchdog.restore.execute": { minRole: "admin" },
  "watchdog.restore.break_glass": { minRole: "admin" },
  "watchdog.vault.view": { minRole: "admin" },
  "watchdog.vault.create": { minRole: "admin" },
  "watchdog.vault.edit": { minRole: "admin" },
  "watchdog.vault.reveal": { minRole: "admin" },
  "watchdog.vault.copy": { minRole: "admin" },
  "watchdog.vault.rotate": { minRole: "admin" },
  "watchdog.security.view": { minRole: "admin" },
  "watchdog.audit.view": { minRole: "admin" },
  "watchdog.settings.manage": { minRole: "admin" },
  "watchdog.health.view": { minRole: "admin" },
  "hrm.view": { minRole: "readonly" },
  "hrm.people.manage": { minRole: "manager" },
  "hrm.schedules.manage": { minRole: "manager" },
  "hrm.locations.manage": { minRole: "manager" },
  "hrm.messages.manage": { minRole: "staff" },
  "hrm.settings.manage": { minRole: "admin" },
  "grants.view": { minRole: "readonly" },
  "grants.create": { minRole: "manager" },
  "grants.edit": { minRole: "staff" },
  "grants.delete": { minRole: "manager" },
  "grants.manage_funders": { minRole: "manager" },
  "grants.manage_tasks": { minRole: "staff" },
  "grants.manage_resources": { minRole: "staff" },
  "grants.manage_deadlines": { minRole: "staff" },
  "grants.record_decision": { minRole: "manager" },
  "grants.link_received_award": { minRole: "manager" },
  "steward_paths.view": { minRole: "readonly" },
  "steward_paths.create": { minRole: "manager" },
  "steward_paths.edit": { minRole: "manager" },
  "steward_paths.activate": { minRole: "manager" },
  "steward_paths.archive": { minRole: "manager" },
  "steward_paths.enroll": { minRole: "staff" },
  "steward_paths.pause": { minRole: "staff" },
  "steward_paths.manage_all": { minRole: "admin" },
  "steward_paths.process_due_steps": { minRole: "admin" },
  "steward_paths.email_auto_send": { minRole: "admin" },
  "letters.view": { minRole: "readonly" },
  "letters.create": { minRole: "manager" },
  "letters.edit": { minRole: "manager" },
  "letters.archive": { minRole: "manager" },
  "letters.generate": { minRole: "staff" },
  "letters.generate_batch": { minRole: "manager" },
  "letters.manage_print_queue": { minRole: "staff" },
  "letters.manage_mail_queue": { minRole: "staff" },
  "letters.manage_signatures": { minRole: "manager" },
  "letters.manage_branding": { minRole: "manager" },
  "letters.create_email_draft": { minRole: "staff" },
  "letters.export_pdf": { minRole: "staff" },
  "letters.view_sensitive_merge_data": { minRole: "manager" },
  "letters.manage_all": { minRole: "admin" },
  "oyama_password.view": { minRole: "readonly" },
  "oyama_password.create": { minRole: "staff" },
  "oyama_password.edit": { minRole: "staff" },
  "oyama_password.delete": { minRole: "manager" },
  "oyama_password.reveal": { minRole: "staff" },
  "oyama_password.share": { minRole: "manager" },
  "oyama_password.backup": { minRole: "admin" },
  "oyama_password.restore": { minRole: "admin" },
};

/**
 * Returns true when a role satisfies or exceeds a minimum role in hierarchy.
 * Lower index in ROLE_HIERARCHY means more privilege.
 */
export function roleMeetsMinimum(role: string, minRole: UserRole): boolean {
  const roleIndex = ROLE_HIERARCHY.indexOf(role as UserRole);
  const minIndex = ROLE_HIERARCHY.indexOf(minRole);
  if (roleIndex === -1 || minIndex === -1) return false;
  return roleIndex <= minIndex;
}

/**
 * Evaluates the default role-based permission policy for a key.
 * Explicit grants/denials are handled separately by middleware using UserPermission rows.
 */
export function hasDefaultPermission(role: string, permission: PermissionKey): boolean {
  const policy = PERMISSION_DEFAULTS[permission];
  return roleMeetsMinimum(role, policy.minRole);
}
