"use client";

import Link from "next/link";
import type { TriviaEvent } from "@/app/apps/trivia/lib/trivia-types";

/** Visual run-of-show for non-technical producers to inspect every round before doors open. */
export default function TriviaGameMap({ event }: { event: TriviaEvent }) {
  const questionCount = event.rounds.reduce((count, round) => count + round.questions.length, 0);
  return <section className="border border-[#d1c7e8] bg-white"><header className="flex flex-wrap items-center justify-between gap-3 border-b border-[#d1c7e8] bg-[#f6f2ff] px-4 py-3"><div><p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-[#5b3f9b]">Visual game map</p><h2 className="mt-1 text-lg font-semibold text-slate-900">Your event, from welcome to winner</h2><p className="mt-1 text-sm text-slate-600">{event.rounds.length} rounds · {questionCount} questions. Open a projector preview before the room arrives.</p></div><Link href={`/apps/trivia/display/${event.id}`} target="_blank" className="bg-[#5b3f9b] px-3 py-2 text-sm font-semibold text-white hover:bg-[#4a327f]">Preview projector</Link></header><div className="overflow-x-auto p-4"><div className="flex min-w-max items-stretch gap-3"><div className="w-40 border border-[#d1c7e8] bg-[#f6f2ff] p-3"><p className="text-xs font-semibold text-[#5b3f9b]">01 · Welcome</p><p className="mt-2 text-xs text-slate-600">Check-in, welcome screen, and rules.</p></div>{event.rounds.map((round, index) => <article key={round.id} className="w-60 border border-[#d1c7e8] bg-white"><div className="border-b border-[#e7e0f5] bg-[#fbfaff] px-3 py-2"><p className="text-[10px] font-semibold uppercase tracking-wide text-[#5b3f9b]">{String(index + 2).padStart(2, "0")} · {round.roundType.replace("_", " ")}</p><p className="mt-1 text-sm font-semibold text-slate-900">{round.title}</p></div><div className="space-y-1.5 p-3">{round.questions.map((question, questionIndex) => <div key={question.id} className="border-l-2 border-[#8a63d2] bg-[#f6f2ff] px-2 py-1.5"><p className="text-[11px] font-semibold text-slate-800">Q{questionIndex + 1} · {question.questionType.replace("_", " ")}</p><p className="mt-0.5 line-clamp-2 text-xs text-slate-600">{question.prompt || "Question still needs a prompt"}</p><p className="mt-1 text-[10px] text-[#5b3f9b]">{question.points} pts · {question.timeLimitSec}s {question.mediaUrl ? "· media ready" : ""}</p></div>)}{round.questions.length === 0 ? <p className="border border-dashed border-[#c8b9e5] p-2 text-xs text-slate-500">No questions yet</p> : null}</div></article>)}<div className="w-40 border border-[#d1c7e8] bg-[#f6f2ff] p-3"><p className="text-xs font-semibold text-[#5b3f9b]">Finale</p><p className="mt-2 text-xs text-slate-600">Leaderboard, tiebreaker, and winner screen.</p></div></div></div></section>;
}
