-- AlterTable
ALTER TABLE `Activity` MODIFY `type` ENUM('DONATION', 'TASK_COMPLETED', 'EMAIL_SENT', 'EMAIL_RECEIVED', 'CALL', 'MEETING', 'NOTE', 'EVENT_REGISTRATION', 'EVENT_ATTENDANCE', 'VOLUNTEER_HOURS', 'PLEDGE_MADE') NOT NULL;
