// Seed help content for CRM-scoped onboarding, task guidance, and troubleshooting.

import type { HelpArticle } from "@/app/help-content/types";

/** Shared image placeholder reused by first-pass article examples. */
const GUIDE_IMAGE = "/branding/oyama-mark-64.png";

/** Published Help App seed articles for donor, events, compassion, and global workflows. */
export const HELP_ARTICLES: HelpArticle[] = [
  {
    id: "help-donor-add-constituent",
    title: "How To Add A Constituent In Donor CRM",
    slug: "donor-add-constituent",
    crmScope: "donor",
    category: "Daily Tasks",
    summary: "Create a new constituent profile and validate that it appears in list and timeline views.",
    body: "Open Constituents, select Add Constituent, complete contact details, and save. Verify communication preferences and stewardship tags before closing.",
    tags: ["donor", "constituents", "getting-started", "daily-task"],
    estimatedReadTime: "4 min",
    difficulty: "beginner",
    role: "staff",
    images: [{ id: "img-donor-add-1", url: GUIDE_IMAGE, alt: "Donor CRM add constituent form", caption: "Add constituent form overview." }],
    walkthroughSteps: [
      { id: "dacs-1", title: "Open Constituents", instruction: "From the sidebar, click Constituents.", targetRoute: "/constituents", order: 1 },
      { id: "dacs-2", title: "Create Record", instruction: "Click Add Constituent and enter profile details.", order: 2 },
      { id: "dacs-3", title: "Save", instruction: "Save and confirm the new profile appears in the list.", order: 3 },
    ],
    relatedArticles: ["help-donor-import-csv", "help-donor-livecom"],
    lastUpdated: "2026-05-11",
    lastReviewed: "2026-05-11",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-donor-import-csv",
    title: "Import Donor Data From CSV",
    slug: "donor-import-csv",
    crmScope: "donor",
    category: "Imports & Exports",
    summary: "Upload CSV, map fields, validate required values, and review duplicate merge suggestions safely.",
    body: "Use Data Tools import flow in this order: Upload, Preview, Map Fields, Validate, Duplicate Review, Confirm Import, Review Results.",
    tags: ["donor", "import", "csv", "data-quality", "duplicates"],
    estimatedReadTime: "7 min",
    difficulty: "intermediate",
    role: "admin",
    walkthroughSteps: [
      { id: "dic-1", title: "Open Data Tools", instruction: "Navigate to Data Tools and choose import.", targetRoute: "/data-tools", order: 1 },
      { id: "dic-2", title: "Map Fields", instruction: "Map incoming columns to CRM fields and fix warnings.", order: 2 },
      { id: "dic-3", title: "Review Duplicates", instruction: "Confirm merge suggestions before import confirmation.", order: 3 },
    ],
    relatedArticles: ["help-global-permissions", "help-donor-add-constituent"],
    lastUpdated: "2026-05-11",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-donor-site-embeds",
    title: "Configure Site Embeds And Header Code Injection",
    slug: "donor-site-embeds",
    crmScope: "donor",
    category: "Website Embeds",
    summary: "Generate secure tokenized snippets, configure allow-listed domains, and test public loader health.",
    body: "Use Settings > Site Embeds to manage website connection metadata, LiveCom launcher settings, and script health checks. Install generated head or footer snippets only.",
    tags: ["site-embeds", "header-code", "footer-code", "livecom", "campaign-meter"],
    estimatedReadTime: "6 min",
    difficulty: "intermediate",
    role: "admin",
    images: [{ id: "img-site-embed-1", url: GUIDE_IMAGE, alt: "Site embeds manager", caption: "Website connection and snippet controls." }],
    walkthroughSteps: [
      { id: "dse-1", title: "Open Site Embeds", instruction: "Go to Settings and open Site Embeds.", targetRoute: "/settings/site-embeds", order: 1 },
      { id: "dse-2", title: "Set Domains", instruction: "Set primary and allowed domains for secure script execution.", order: 2 },
      { id: "dse-3", title: "Install Snippet", instruction: "Copy generated head or footer snippet into your website template.", order: 3 },
      { id: "dse-4", title: "Run Connection Test", instruction: "Use Test Connection to verify ping and allow-list status.", order: 4 },
    ],
    relatedArticles: ["help-donor-livecom"],
    lastUpdated: "2026-05-11",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-donor-livecom",
    title: "Use LiveCom For Website Conversations",
    slug: "donor-livecom-workspace",
    crmScope: "donor",
    category: "Communication",
    summary: "Capture website messages in LiveCom and convert interactions into follow-up tasks.",
    body: "LiveCom centralizes website chat and interaction updates. Track status, assign ownership, and connect interactions to constituent timelines.",
    tags: ["livecom", "communication", "inbox", "website-chat"],
    estimatedReadTime: "5 min",
    difficulty: "beginner",
    role: "staff",
    relatedArticles: ["help-donor-site-embeds"],
    lastUpdated: "2026-05-11",
    status: "published",
    featureReadiness: "Partially Working",
  },
  {
    id: "help-events-create-event",
    title: "Create And Activate An Event Workspace",
    slug: "events-create-event",
    crmScope: "events",
    category: "Getting Started",
    summary: "Create an event record, choose it in workspace selector, and open scoped operations tools.",
    body: "Events CRM uses event-first navigation. Start in Events registry, then choose your event from Workspace Selector before opening scoped tools.",
    tags: ["events", "workspace-selector", "event-scoped"],
    estimatedReadTime: "5 min",
    difficulty: "beginner",
    role: "staff",
    walkthroughSteps: [
      { id: "ece-1", title: "Create Event", instruction: "Open Events and create your event profile.", targetRoute: "/events/events", order: 1 },
      { id: "ece-2", title: "Select Workspace", instruction: "Open Workspace Selector and choose active event.", targetRoute: "/events/workspace", order: 2 },
      { id: "ece-3", title: "Open Scoped Tool", instruction: "Navigate to guests, tables, or check-in from selected event context.", order: 3 },
    ],
    relatedArticles: ["help-events-seating", "help-events-checkin"],
    lastUpdated: "2026-05-11",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-events-seating",
    title: "Manage Tables And Seating Assignments",
    slug: "events-table-seating",
    crmScope: "events",
    category: "Events",
    summary: "Build table layouts, assign guests, and monitor open seats before event day.",
    body: "Use Tables to set capacities, sponsor hosts, and assignments. Review over-capacity warnings and unassigned guests each day before check-in.",
    tags: ["events", "table-seating", "guests", "capacity"],
    estimatedReadTime: "6 min",
    difficulty: "intermediate",
    role: "staff",
    relatedArticles: ["help-events-checkin"],
    lastUpdated: "2026-05-11",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-events-checkin",
    title: "Run Event Check-In Operations",
    slug: "events-check-in-guide",
    crmScope: "events",
    category: "Daily Tasks",
    summary: "Use check-in workflows to process arrivals and track live attendance status.",
    body: "Open Check-In from an event-scoped route. Search guest roster, validate ticket status, and complete check-in actions in real time.",
    tags: ["events", "check-in", "guests", "operations"],
    estimatedReadTime: "4 min",
    difficulty: "beginner",
    role: "volunteer",
    lastUpdated: "2026-05-11",
    status: "published",
    featureReadiness: "Partially Working",
  },
  {
    id: "help-compassion-add-client",
    title: "Add A Client In Compassion CRM",
    slug: "compassion-add-client",
    crmScope: "compassion",
    category: "Clients",
    summary: "Create a new client profile with privacy-aware intake details and status tracking.",
    body: "Use Clients list to add a new profile. Keep sensitive fields protected and confirm intake timeline status.",
    tags: ["compassion", "clients", "intake", "privacy"],
    estimatedReadTime: "5 min",
    difficulty: "beginner",
    role: "staff",
    relatedArticles: ["help-compassion-appointments", "help-compassion-import"],
    lastUpdated: "2026-05-11",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-compassion-appointments",
    title: "Schedule And Manage Appointments",
    slug: "compassion-appointments-workspace",
    crmScope: "compassion",
    category: "Appointments",
    summary: "Use calendar and list views to schedule, reschedule, and complete appointments safely.",
    body: "Appointments workspace supports drag-drop scheduling, conflict detection, and quick status updates. Confirm client and staff assignment before saving.",
    tags: ["compassion", "appointments", "calendar", "rescheduling"],
    estimatedReadTime: "7 min",
    difficulty: "intermediate",
    role: "staff",
    walkthroughSteps: [
      { id: "caw-1", title: "Open Appointments", instruction: "Navigate to Compassion Appointments workspace.", targetRoute: "/compassion/appointments", order: 1 },
      { id: "caw-2", title: "Create Appointment", instruction: "Use Schedule Appointment button and complete required fields.", order: 2 },
      { id: "caw-3", title: "Confirm Calendar", instruction: "Verify event placement and status in calendar/list views.", order: 3 },
    ],
    relatedArticles: ["help-compassion-add-client"],
    lastUpdated: "2026-05-11",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-compassion-import",
    title: "Import Clients Safely",
    slug: "compassion-client-import",
    crmScope: "compassion",
    category: "Imports & Exports",
    summary: "Import client CSV files with validation guards for sensitive data boundaries.",
    body: "Compassion imports run strict validation and strip restricted identifiers. Use preview, mapping, validation, and duplicate review before commit.",
    tags: ["compassion", "import", "clients", "privacy", "validation"],
    estimatedReadTime: "6 min",
    difficulty: "intermediate",
    role: "admin",
    lastUpdated: "2026-05-11",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-global-login",
    title: "Get Started With OyamaCRM",
    slug: "global-getting-started",
    crmScope: "global",
    category: "Getting Started",
    summary: "Learn module switching, dashboard basics, and where to find key workspace tools.",
    body: "After login, use module switcher in TopBar to move between Donor, Events, and Compassion workspaces. Use Help from any module to get scoped guidance.",
    tags: ["global", "getting-started", "module-switcher", "dashboard"],
    estimatedReadTime: "3 min",
    difficulty: "beginner",
    role: "all",
    relatedArticles: ["help-global-permissions"],
    lastUpdated: "2026-05-11",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-global-permissions",
    title: "Understand Roles, Permissions, And Feature Readiness",
    slug: "global-permissions-and-readiness",
    crmScope: "global",
    category: "Security & Permissions",
    summary: "Review access boundaries and how feature readiness labels impact staff expectations.",
    body: "Roles control what each user can view and edit. Help articles may include feature readiness labels: Working, Partially Working, Demo Only, Broken, Not Implemented.",
    tags: ["global", "permissions", "security", "feature-readiness"],
    estimatedReadTime: "5 min",
    difficulty: "intermediate",
    role: "admin",
    lastUpdated: "2026-05-11",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-global-steward-ai",
    title: "Use Steward AI With Official Help Sources",
    slug: "global-steward-ai-help",
    crmScope: "global",
    category: "Steward AI",
    summary: "Use Steward AI for guidance while relying on published Help App content as trusted documentation.",
    body: "Steward AI can later consume Help App content for grounded responses. For now, use Help guides directly for confirmed workflows and current feature status.",
    tags: ["global", "steward-ai", "rag", "guidance"],
    estimatedReadTime: "4 min",
    difficulty: "intermediate",
    role: "all",
    lastUpdated: "2026-05-11",
    status: "published",
    featureReadiness: "Partially Working",
  },
];
