// Seed help content for CRM-scoped onboarding, task guidance, and troubleshooting.

import type { HelpArticle } from "@/app/help-content/types";

/** Shared image placeholder reused by first-pass article examples. */
const GUIDE_IMAGE = "/branding/oyama-mark-64.png";

/** Published Help App seed articles for donor, events, compassion, and global workflows. */
export const HELP_ARTICLES: HelpArticle[] = [
  {
    id: "help-donor-add-constituent",
    title: "How To Add A Constituent In Donor CRM",
    slug: "donor-add-constituent",
    crmScope: "donor",
    category: "Daily Tasks",
    summary: "Create a new constituent profile and validate that it appears in list and timeline views.",
    body: "Open Constituents, select Add Constituent, complete contact details, and save. Verify communication preferences and stewardship tags before closing.",
    tags: ["donor", "constituents", "getting-started", "daily-task"],
    estimatedReadTime: "4 min",
    difficulty: "beginner",
    role: "staff",
    images: [{ id: "img-donor-add-1", url: GUIDE_IMAGE, alt: "Donor CRM add constituent form", caption: "Add constituent form overview." }],
    walkthroughSteps: [
      { id: "dacs-1", title: "Open Constituents", instruction: "From the sidebar, click Constituents.", targetRoute: "/constituents", order: 1 },
      { id: "dacs-2", title: "Create Record", instruction: "Click Add Constituent and enter profile details.", order: 2 },
      { id: "dacs-3", title: "Save", instruction: "Save and confirm the new profile appears in the list.", order: 3 },
    ],
    relatedArticles: ["help-donor-import-csv", "help-donor-livecom"],
    lastUpdated: "2026-05-11",
    lastReviewed: "2026-05-11",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-donor-import-csv",
    title: "Import Donor Data From CSV",
    slug: "donor-import-csv",
    crmScope: "donor",
    category: "Imports & Exports",
    summary: "Upload CSV, map fields, validate required values, and review duplicate merge suggestions safely.",
    body: "Use Data Tools import flow in this order: Upload, Preview, Map Fields, Validate, Duplicate Review, Confirm Import, Review Results.",
    tags: ["donor", "import", "csv", "data-quality", "duplicates"],
    estimatedReadTime: "7 min",
    difficulty: "intermediate",
    role: "admin",
    walkthroughSteps: [
      { id: "dic-1", title: "Open Data Tools", instruction: "Navigate to Data Tools and choose import.", targetRoute: "/data-tools", order: 1 },
      { id: "dic-2", title: "Map Fields", instruction: "Map incoming columns to CRM fields and fix warnings.", order: 2 },
      { id: "dic-3", title: "Review Duplicates", instruction: "Confirm merge suggestions before import confirmation.", order: 3 },
    ],
    relatedArticles: ["help-global-permissions", "help-donor-add-constituent"],
    lastUpdated: "2026-05-11",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-donor-site-embeds",
    title: "Configure Site Embeds And Header Code Injection",
    slug: "donor-site-embeds",
    crmScope: "donor",
    category: "Website Embeds",
    summary: "Generate secure tokenized snippets, configure allow-listed domains, and test public loader health.",
    body: "Use Settings > Site Embeds to manage website connection metadata, LiveCom launcher settings, and script health checks. Install generated head or footer snippets only.",
    tags: ["site-embeds", "header-code", "footer-code", "livecom", "campaign-meter"],
    estimatedReadTime: "6 min",
    difficulty: "intermediate",
    role: "admin",
    images: [{ id: "img-site-embed-1", url: GUIDE_IMAGE, alt: "Site embeds manager", caption: "Website connection and snippet controls." }],
    walkthroughSteps: [
      { id: "dse-1", title: "Open Site Embeds", instruction: "Go to Settings and open Site Embeds.", targetRoute: "/settings/site-embeds", order: 1 },
      { id: "dse-2", title: "Set Domains", instruction: "Set primary and allowed domains for secure script execution.", order: 2 },
      { id: "dse-3", title: "Install Snippet", instruction: "Copy generated head or footer snippet into your website template.", order: 3 },
      { id: "dse-4", title: "Run Connection Test", instruction: "Use Test Connection to verify ping and allow-list status.", order: 4 },
    ],
    relatedArticles: ["help-donor-livecom"],
    lastUpdated: "2026-05-11",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-donor-livecom",
    title: "Use LiveCom For Website Conversations",
    slug: "donor-livecom-workspace",
    crmScope: "donor",
    category: "Communication",
    summary: "Capture website messages in LiveCom and convert interactions into follow-up tasks.",
    body: "LiveCom centralizes website chat and interaction updates. Track status, assign ownership, and connect interactions to constituent timelines.",
    tags: ["livecom", "communication", "inbox", "website-chat"],
    estimatedReadTime: "5 min",
    difficulty: "beginner",
    role: "staff",
    relatedArticles: ["help-donor-site-embeds"],
    lastUpdated: "2026-05-11",
    status: "published",
    featureReadiness: "Partially Working",
  },
  {
    id: "help-events-create-event",
    title: "Create And Activate An Event Workspace",
    slug: "events-create-event",
    crmScope: "events",
    category: "Getting Started",
    summary: "Create an event record, choose it in workspace selector, and open scoped operations tools.",
    body: "Events CRM uses event-first navigation. Start in Events registry, then choose your event from Workspace Selector before opening scoped tools.",
    tags: ["events", "workspace-selector", "event-scoped"],
    estimatedReadTime: "5 min",
    difficulty: "beginner",
    role: "staff",
    walkthroughSteps: [
      { id: "ece-1", title: "Create Event", instruction: "Open Events and create your event profile.", targetRoute: "/events/events", order: 1 },
      { id: "ece-2", title: "Select Workspace", instruction: "Open Workspace Selector and choose active event.", targetRoute: "/events/workspace", order: 2 },
      { id: "ece-3", title: "Open Scoped Tool", instruction: "Navigate to guests, tables, or check-in from selected event context.", order: 3 },
    ],
    relatedArticles: ["help-events-seating", "help-events-checkin"],
    lastUpdated: "2026-05-11",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-events-seating",
    title: "Manage Tables And Seating Assignments",
    slug: "events-table-seating",
    crmScope: "events",
    category: "Events",
    summary: "Build table layouts, assign guests, and monitor open seats before event day.",
    body: "Use Tables to set capacities, sponsor hosts, and assignments. Review over-capacity warnings and unassigned guests each day before check-in.",
    tags: ["events", "table-seating", "guests", "capacity"],
    estimatedReadTime: "6 min",
    difficulty: "intermediate",
    role: "staff",
    relatedArticles: ["help-events-checkin"],
    lastUpdated: "2026-05-11",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-events-checkin",
    title: "Run Event Check-In Operations",
    slug: "events-check-in-guide",
    crmScope: "events",
    category: "Daily Tasks",
    summary: "Use check-in workflows to process arrivals and track live attendance status.",
    body: "Open Check-In from an event-scoped route. Search guest roster, validate ticket status, and complete check-in actions in real time.",
    tags: ["events", "check-in", "guests", "operations"],
    estimatedReadTime: "4 min",
    difficulty: "beginner",
    role: "volunteer",
    lastUpdated: "2026-05-11",
    status: "published",
    featureReadiness: "Partially Working",
  },
  {
    id: "help-compassion-add-client",
    title: "Add A Client In Compassion CRM",
    slug: "compassion-add-client",
    crmScope: "compassion",
    category: "Clients",
    summary: "Create a new client profile with privacy-aware intake details and status tracking.",
    body: "Use Clients list to add a new profile. Keep sensitive fields protected and confirm intake timeline status.",
    tags: ["compassion", "clients", "intake", "privacy"],
    estimatedReadTime: "5 min",
    difficulty: "beginner",
    role: "staff",
    relatedArticles: ["help-compassion-appointments", "help-compassion-import"],
    lastUpdated: "2026-05-11",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-compassion-appointments",
    title: "Schedule And Manage Appointments",
    slug: "compassion-appointments-workspace",
    crmScope: "compassion",
    category: "Appointments",
    summary: "Use calendar and list views to schedule, reschedule, and complete appointments safely.",
    body: "Appointments workspace supports drag-drop scheduling, conflict detection, and quick status updates. Confirm client and staff assignment before saving.",
    tags: ["compassion", "appointments", "calendar", "rescheduling"],
    estimatedReadTime: "7 min",
    difficulty: "intermediate",
    role: "staff",
    walkthroughSteps: [
      { id: "caw-1", title: "Open Appointments", instruction: "Navigate to Compassion Appointments workspace.", targetRoute: "/compassion/appointments", order: 1 },
      { id: "caw-2", title: "Create Appointment", instruction: "Use Schedule Appointment button and complete required fields.", order: 2 },
      { id: "caw-3", title: "Confirm Calendar", instruction: "Verify event placement and status in calendar/list views.", order: 3 },
    ],
    relatedArticles: ["help-compassion-add-client"],
    lastUpdated: "2026-05-11",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-compassion-import",
    title: "Import Clients Safely",
    slug: "compassion-client-import",
    crmScope: "compassion",
    category: "Imports & Exports",
    summary: "Import client CSV files with validation guards for sensitive data boundaries.",
    body: "Compassion imports run strict validation and strip restricted identifiers. Use preview, mapping, validation, and duplicate review before commit.",
    tags: ["compassion", "import", "clients", "privacy", "validation"],
    estimatedReadTime: "6 min",
    difficulty: "intermediate",
    role: "admin",
    lastUpdated: "2026-05-11",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-global-login",
    title: "Get Started With OyamaCRM",
    slug: "global-getting-started",
    crmScope: "global",
    category: "Getting Started",
    summary: "Learn module switching, dashboard basics, and where to find key workspace tools.",
    body: "After login, use module switcher in TopBar to move between Donor, Events, and Compassion workspaces. Use Help from any module to get scoped guidance.",
    tags: ["global", "getting-started", "module-switcher", "dashboard"],
    estimatedReadTime: "3 min",
    difficulty: "beginner",
    role: "all",
    relatedArticles: ["help-global-permissions"],
    lastUpdated: "2026-05-11",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-global-permissions",
    title: "Understand Roles, Permissions, And Feature Readiness",
    slug: "global-permissions-and-readiness",
    crmScope: "global",
    category: "Security & Permissions",
    summary: "Review access boundaries and how feature readiness labels impact staff expectations.",
    body: "Roles control what each user can view and edit. Help articles may include feature readiness labels: Working, Partially Working, Demo Only, Broken, Not Implemented.",
    tags: ["global", "permissions", "security", "feature-readiness"],
    estimatedReadTime: "5 min",
    difficulty: "intermediate",
    role: "admin",
    lastUpdated: "2026-05-11",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-global-steward-ai",
    title: "Use Steward AI With Official Help Sources",
    slug: "global-steward-ai-help",
    crmScope: "global",
    category: "Steward AI",
    summary: "Use Steward AI for guidance while relying on published Help App content as trusted documentation.",
    body: "Steward AI can later consume Help App content for grounded responses. For now, use Help guides directly for confirmed workflows and current feature status.",
    tags: ["global", "steward-ai", "rag", "guidance"],
    estimatedReadTime: "4 min",
    difficulty: "intermediate",
    role: "all",
    lastUpdated: "2026-05-11",
    status: "published",
    featureReadiness: "Partially Working",
  },
  {
    id: "help-donor-record-donation",
    title: "Record A Donation In Donor CRM",
    slug: "donor-record-donation",
    crmScope: "donor",
    category: "Daily Tasks",
    summary: "Enter one-time gifts with designation, payment method, and acknowledgment settings.",
    body: "Open Donations, create a new donation, verify constituent, amount, designation, and payment method, then save and confirm receipt/acknowledgment status.",
    tags: ["donor", "donations", "gift-entry", "daily-task"],
    estimatedReadTime: "5 min",
    difficulty: "beginner",
    role: "staff",
    walkthroughSteps: [
      { id: "drd-1", title: "Open Donations", instruction: "Go to Donations from the sidebar.", targetRoute: "/donations", order: 1 },
      { id: "drd-2", title: "Create Donation", instruction: "Click New Donation and complete required fields.", order: 2 },
      { id: "drd-3", title: "Confirm Timeline", instruction: "Verify the donation appears in donor history.", order: 3 },
    ],
    relatedArticles: ["help-donor-add-constituent", "help-donor-recurring-gifts"],
    lastUpdated: "2026-05-16",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-donor-recurring-gifts",
    title: "Set Up Recurring Gifts",
    slug: "donor-recurring-gifts",
    crmScope: "donor",
    category: "Donations",
    summary: "Configure recurring schedules and monitor active, paused, and failed recurring gifts.",
    body: "Create recurring donation plans from donor or donation workflows, set interval and start date, and monitor recurring health indicators for failed payments.",
    tags: ["donor", "recurring", "donations", "stewardship"],
    estimatedReadTime: "6 min",
    difficulty: "intermediate",
    role: "staff",
    relatedArticles: ["help-donor-record-donation"],
    lastUpdated: "2026-05-16",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-donor-send-email-campaign",
    title: "Build And Send A Donor Email Campaign",
    slug: "donor-send-email-campaign",
    crmScope: "donor",
    category: "Communication",
    summary: "Create draft-first campaigns, run test sends, and launch with compliance checks.",
    body: "Use Communications to create a draft campaign, verify audience and compliance tokens, run send-test, then send now or schedule once approved.",
    tags: ["communications", "email", "campaign", "draft-first"],
    estimatedReadTime: "8 min",
    difficulty: "intermediate",
    role: "staff",
    walkthroughSteps: [
      { id: "dsec-1", title: "Open Communications", instruction: "Navigate to Communications workspace.", targetRoute: "/communications", order: 1 },
      { id: "dsec-2", title: "Create Campaign", instruction: "Set audience, subject, and content in draft mode.", order: 2 },
      { id: "dsec-3", title: "Test And Launch", instruction: "Run send-test and then send or schedule.", order: 3 },
    ],
    relatedArticles: ["help-global-email-provider-setup", "help-donor-manage-preferences"],
    lastUpdated: "2026-05-16",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-donor-manage-preferences",
    title: "Manage Donor Email Preferences And Unsubscribes",
    slug: "donor-email-preferences",
    crmScope: "donor",
    category: "Communication",
    summary: "Handle opt-outs, category preferences, and suppression-safe sending behavior.",
    body: "Before outreach, verify do-not-contact flags and email preference categories. Respect unsubscribe settings and never force-send suppressed recipients.",
    tags: ["email", "preferences", "unsubscribe", "compliance"],
    estimatedReadTime: "6 min",
    difficulty: "intermediate",
    role: "admin",
    relatedArticles: ["help-donor-send-email-campaign"],
    lastUpdated: "2026-05-16",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-donor-letters-print-queue",
    title: "Generate Letters And Manage Print Queue",
    slug: "donor-letters-print-queue",
    crmScope: "donor",
    category: "Letters & Printables",
    summary: "Move letters through review, print, and mail queue stages with clear ownership.",
    body: "Use Letters and Printables to draft or generate letters, review content, then move queue items through approved, printed, and mailed statuses.",
    tags: ["letters", "printables", "mail", "queue"],
    estimatedReadTime: "7 min",
    difficulty: "intermediate",
    role: "staff",
    walkthroughSteps: [
      { id: "dlpq-1", title: "Open Letters", instruction: "Go to Letters and Printables workspace.", targetRoute: "/letters-printables", order: 1 },
      { id: "dlpq-2", title: "Approve Draft", instruction: "Review generated content and approve for print.", order: 2 },
      { id: "dlpq-3", title: "Advance Queue", instruction: "Move queue items from printed to mailed.", order: 3 },
    ],
    relatedArticles: ["help-donor-send-email-campaign"],
    lastUpdated: "2026-05-16",
    status: "published",
    featureReadiness: "Partially Working",
  },
  {
    id: "help-donor-create-steward-task",
    title: "Create Stewardship Follow-Up Tasks",
    slug: "donor-stewardship-tasks",
    crmScope: "donor",
    category: "Task & Workflow",
    summary: "Assign donor follow-up tasks with due dates, priority, and relationship context.",
    body: "Use Tasks to create clear follow-up actions linked to constituents. Include due date, owner, and next-step details for stewardship continuity.",
    tags: ["tasks", "stewardship", "follow-up", "donor"],
    estimatedReadTime: "5 min",
    difficulty: "beginner",
    role: "staff",
    walkthroughSteps: [
      { id: "dst-1", title: "Open Tasks", instruction: "Navigate to Tasks workspace.", targetRoute: "/tasks", order: 1 },
      { id: "dst-2", title: "Create Task", instruction: "Set title, assignee, due date, and linked constituent.", order: 2 },
      { id: "dst-3", title: "Track Completion", instruction: "Update task status after outreach is complete.", order: 3 },
    ],
    relatedArticles: ["help-donor-add-constituent"],
    lastUpdated: "2026-05-16",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-donor-build-report",
    title: "Build A Donor Report And Export Results",
    slug: "donor-report-builder",
    crmScope: "donor",
    category: "Reporting",
    summary: "Create filtered report views for giving, retention, and stewardship progress.",
    body: "Open Reports, choose a report type or builder flow, apply filters, validate row counts, and export CSV/Excel for stakeholder review.",
    tags: ["reports", "analytics", "export", "retention"],
    estimatedReadTime: "7 min",
    difficulty: "intermediate",
    role: "admin",
    walkthroughSteps: [
      { id: "drb-1", title: "Open Reports", instruction: "Go to Reports workspace.", targetRoute: "/reports", order: 1 },
      { id: "drb-2", title: "Apply Filters", instruction: "Filter by date range, campaign, or designation.", order: 2 },
      { id: "drb-3", title: "Export", instruction: "Export data after validating totals.", order: 3 },
    ],
    relatedArticles: ["help-global-permissions"],
    lastUpdated: "2026-05-16",
    status: "published",
    featureReadiness: "Partially Working",
  },
  {
    id: "help-donor-grants-workspace",
    title: "Use The Grants Workspace",
    slug: "donor-grants-workspace",
    crmScope: "donor",
    category: "Grants",
    summary: "Track grant research, requirements, deadlines, and writing tasks without mixing donation ledger data.",
    body: "Use Grants as opportunity and writing workflow space. Record awarded funds through donation handoff flow only when money is received.",
    tags: ["grants", "deadlines", "writing", "research"],
    estimatedReadTime: "6 min",
    difficulty: "intermediate",
    role: "staff",
    walkthroughSteps: [
      { id: "dgw-1", title: "Open Grants", instruction: "Navigate to Grants workspace.", targetRoute: "/grants", order: 1 },
      { id: "dgw-2", title: "Add Opportunity", instruction: "Create funder opportunity with requirements and due dates.", order: 2 },
      { id: "dgw-3", title: "Assign Writing Tasks", instruction: "Create tasks for drafting and review deadlines.", order: 3 },
    ],
    lastUpdated: "2026-05-16",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-donor-quickbooks-queue",
    title: "Queue Donations For QuickBooks Sync",
    slug: "donor-quickbooks-sync-queue",
    crmScope: "donor",
    category: "Integrations",
    summary: "Use opt-in queue-based QuickBooks sync with manual review before sync actions.",
    body: "Enable QuickBooks plugin, opt-in donation queue entries, and run manual sync. Failed rows can be edited and retried; synced rows remain immutable.",
    tags: ["quickbooks", "integrations", "queue", "finance"],
    estimatedReadTime: "8 min",
    difficulty: "intermediate",
    role: "admin",
    walkthroughSteps: [
      { id: "dqb-1", title: "Enable Plugin", instruction: "Open Settings > Plugins and enable QuickBooks.", targetRoute: "/settings/plugins", order: 1 },
      { id: "dqb-2", title: "Open QB Queue", instruction: "Open QuickBooks Sync workspace.", targetRoute: "/quickbooks-sync", order: 2 },
      { id: "dqb-3", title: "Run Manual Sync", instruction: "Sync individual rows or sync-all after review.", order: 3 },
    ],
    lastUpdated: "2026-05-16",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-events-register-guests",
    title: "Register Guests For An Event",
    slug: "events-register-guests",
    crmScope: "events",
    category: "Events",
    summary: "Create guest records, assign ticket types, and verify RSVP/payment status before event day.",
    body: "Use event-scoped guest tools to add individual or batch guests and keep RSVP and payment status current for check-in readiness.",
    tags: ["events", "guests", "registration", "rsvp"],
    estimatedReadTime: "6 min",
    difficulty: "beginner",
    role: "staff",
    walkthroughSteps: [
      { id: "erg-1", title: "Open Event Workspace", instruction: "Select active event from workspace selector.", targetRoute: "/events/workspace", order: 1 },
      { id: "erg-2", title: "Add Guests", instruction: "Use guest registration flow to add attendees.", order: 2 },
      { id: "erg-3", title: "Verify Status", instruction: "Confirm RSVP and payment status columns are complete.", order: 3 },
    ],
    relatedArticles: ["help-events-checkin"],
    lastUpdated: "2026-05-16",
    status: "published",
    featureReadiness: "Partially Working",
  },
  {
    id: "help-events-page-builder",
    title: "Create Event Pages In Events Page Builder",
    slug: "events-page-builder",
    crmScope: "events",
    category: "Events",
    summary: "Use page builder for event landing pages and registration messaging workflows.",
    body: "Open Events Page Builder to create event pages, configure sections, and validate links before publishing.",
    tags: ["events", "page-builder", "website", "registration"],
    estimatedReadTime: "6 min",
    difficulty: "intermediate",
    role: "staff",
    walkthroughSteps: [
      { id: "epb-1", title: "Open Page Builder", instruction: "Navigate to Events Page Builder.", targetRoute: "/events/page-builder", order: 1 },
      { id: "epb-2", title: "Build Sections", instruction: "Add event details, schedule, and call-to-action content.", order: 2 },
      { id: "epb-3", title: "Preview", instruction: "Preview page before publish handoff.", order: 3 },
    ],
    lastUpdated: "2026-05-16",
    status: "published",
    featureReadiness: "Partially Working",
  },
  {
    id: "help-events-reports",
    title: "Run Cross-Event Reports",
    slug: "events-cross-event-reports",
    crmScope: "events",
    category: "Reporting",
    summary: "Compare attendance, revenue, and check-in metrics across multiple events.",
    body: "Use global Events Reports for cross-event analysis and trend tracking. Keep event-scoped tools for single-event operations only.",
    tags: ["events", "reports", "attendance", "revenue"],
    estimatedReadTime: "5 min",
    difficulty: "intermediate",
    role: "admin",
    walkthroughSteps: [
      { id: "eer-1", title: "Open Reports", instruction: "Navigate to Events Reports.", targetRoute: "/events/reports", order: 1 },
      { id: "eer-2", title: "Select Date Range", instruction: "Apply date/event filters for the comparison window.", order: 2 },
      { id: "eer-3", title: "Export", instruction: "Export summarized report views when needed.", order: 3 },
    ],
    relatedArticles: ["help-events-create-event"],
    lastUpdated: "2026-05-16",
    status: "published",
    featureReadiness: "Partially Working",
  },
  {
    id: "help-compassion-open-case",
    title: "Open A New Compassion Case",
    slug: "compassion-open-case",
    crmScope: "compassion",
    category: "Cases",
    summary: "Create a case linked to a client and track case stage safely within client boundaries.",
    body: "Use Cases workspace to open a new case, assign owner, and set initial status. Keep all service records scoped to the linked client profile.",
    tags: ["compassion", "cases", "client-scope", "workflow"],
    estimatedReadTime: "6 min",
    difficulty: "beginner",
    role: "staff",
    walkthroughSteps: [
      { id: "coc-1", title: "Open Cases", instruction: "Navigate to Compassion Cases.", targetRoute: "/compassion/cases", order: 1 },
      { id: "coc-2", title: "Create Case", instruction: "Select client, owner, and initial case details.", order: 2 },
      { id: "coc-3", title: "Verify Client Scope", instruction: "Confirm case appears in the client workspace timeline.", order: 3 },
    ],
    relatedArticles: ["help-compassion-add-client"],
    lastUpdated: "2026-05-16",
    status: "published",
    featureReadiness: "Partially Working",
  },
  {
    id: "help-compassion-follow-up-tasks",
    title: "Manage Compassion Follow-Up Tasks",
    slug: "compassion-follow-up-tasks",
    crmScope: "compassion",
    category: "Task & Workflow",
    summary: "Assign follow-up actions for client appointments, referrals, and case reviews.",
    body: "Use Tasks and Follow Ups in Compassion to assign ownership and due dates. Keep task notes privacy-safe and client-specific.",
    tags: ["compassion", "tasks", "follow-ups", "case-management"],
    estimatedReadTime: "5 min",
    difficulty: "beginner",
    role: "staff",
    walkthroughSteps: [
      { id: "cft-1", title: "Open Follow Ups", instruction: "Navigate to Follow Ups workspace.", targetRoute: "/compassion/follow-ups", order: 1 },
      { id: "cft-2", title: "Create Task", instruction: "Add task title, due date, and assigned staff member.", order: 2 },
      { id: "cft-3", title: "Close Task", instruction: "Mark complete when outreach is finished.", order: 3 },
    ],
    relatedArticles: ["help-compassion-appointments"],
    lastUpdated: "2026-05-16",
    status: "published",
    featureReadiness: "Partially Working",
  },
  {
    id: "help-compassion-public-scheduling-widget",
    title: "Configure Public Scheduling Widget",
    slug: "compassion-public-scheduling-widget",
    crmScope: "compassion",
    category: "Appointments",
    summary: "Publish appointment slots using server-generated availability and submit-time validation.",
    body: "Configure appointment widget policy, publish tokenized embed, and verify slot generation endpoint before sharing public links.",
    tags: ["compassion", "appointments", "widget", "public-scheduling"],
    estimatedReadTime: "7 min",
    difficulty: "advanced",
    role: "admin",
    walkthroughSteps: [
      { id: "cpsw-1", title: "Open Appointment Settings", instruction: "Configure scheduling policy and availability windows.", targetRoute: "/compassion/appointments", order: 1 },
      { id: "cpsw-2", title: "Publish Widget", instruction: "Generate widget token and embed snippet.", order: 2 },
      { id: "cpsw-3", title: "Validate Slots", instruction: "Confirm public slot endpoint returns expected results.", order: 3 },
    ],
    relatedArticles: ["help-compassion-appointments"],
    lastUpdated: "2026-05-16",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-global-email-provider-setup",
    title: "Set Up System Email Provider",
    slug: "global-email-provider-setup",
    crmScope: "global",
    category: "System Setup",
    summary: "Configure standard SMTP, Microsoft 365 SMTP, or Microsoft Graph provider settings.",
    body: "Open Organization Settings, choose outbound provider, complete credentials, run provider test send, and save before launching campaigns.",
    tags: ["smtp", "microsoft-graph", "email", "settings"],
    estimatedReadTime: "8 min",
    difficulty: "intermediate",
    role: "admin",
    walkthroughSteps: [
      { id: "ges-1", title: "Open Organization Settings", instruction: "Navigate to Settings > Organization.", targetRoute: "/settings/organization", order: 1 },
      { id: "ges-2", title: "Choose Provider", instruction: "Select SMTP, Microsoft 365 SMTP, or Microsoft Graph.", order: 2 },
      { id: "ges-3", title: "Run Provider Test", instruction: "Send provider test email and confirm success.", order: 3 },
    ],
    relatedArticles: ["help-donor-send-email-campaign"],
    lastUpdated: "2026-05-16",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-global-microsoft-graph-connect",
    title: "Connect Microsoft Graph For Outbound Email",
    slug: "global-microsoft-graph-connect",
    crmScope: "global",
    category: "System Setup",
    summary: "Complete OAuth connect flow and verify Graph send permissions for production email.",
    body: "Save tenant/client credentials, start OAuth auth-uri flow, complete callback connect, and run provider test with Graph mode.",
    tags: ["microsoft-graph", "oauth", "mail-send", "connectors"],
    estimatedReadTime: "9 min",
    difficulty: "advanced",
    role: "admin",
    walkthroughSteps: [
      { id: "gmgc-1", title: "Save Graph Credentials", instruction: "Enter tenant ID, client ID, and secret.", targetRoute: "/settings/organization", order: 1 },
      { id: "gmgc-2", title: "Connect OAuth", instruction: "Run Connect Microsoft Graph and complete consent.", order: 2 },
      { id: "gmgc-3", title: "Verify Provider Test", instruction: "Run provider test and confirm Graph mode response.", order: 3 },
    ],
    relatedArticles: ["help-global-email-provider-setup"],
    lastUpdated: "2026-05-16",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-global-troubleshoot-help-search",
    title: "Troubleshoot Help Search And Agent Suggestions",
    slug: "global-help-search-troubleshooting",
    crmScope: "global",
    category: "Troubleshooting",
    summary: "Use scoped filters, route context, and keyword matching to find the right guide quickly.",
    body: "When results look thin, remove restrictive filters, switch scope, and use practical terms like import, check-in, donation, appointment, or report.",
    tags: ["help", "search", "troubleshooting", "agent"],
    estimatedReadTime: "4 min",
    difficulty: "beginner",
    role: "all",
    lastUpdated: "2026-05-16",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-global-steward-help-mode",
    title: "Use Steward Help Mode With Guide Links",
    slug: "global-steward-help-mode",
    crmScope: "global",
    category: "Steward AI",
    summary: "Ask how-to questions in Steward and use linked Help guides for route-by-route execution.",
    body: "Switch Steward to Help mode, ask outcome-oriented questions, then open linked Help guides and route actions directly from the response.",
    tags: ["steward-ai", "help-mode", "guides", "workflow"],
    estimatedReadTime: "4 min",
    difficulty: "beginner",
    role: "all",
    relatedArticles: ["help-global-steward-ai"],
    lastUpdated: "2026-05-16",
    status: "published",
    featureReadiness: "Working",
  },
];
