// Seed help content for CRM-scoped onboarding, task guidance, and troubleshooting.

import type { HelpArticle } from "@/app/help-content/types";

/** Shared image placeholder reused by first-pass article examples. */
const GUIDE_IMAGE = "/branding/oyama-mark-64.png";

/** Published Help App seed articles for donor, events, compassion, and global workflows. */
export const HELP_ARTICLES: HelpArticle[] = [
  {
    id: "help-donor-add-constituent",
    title: "How To Add A Constituent In Donor CRM",
    slug: "donor-add-constituent",
    crmScope: "donor",
    category: "Daily Tasks",
    summary: "Create a new constituent profile and validate that it appears in list and timeline views.",
    body: "Open Constituents, select Add Constituent, complete contact details, and save. Verify communication preferences and stewardship tags before closing.",
    tags: ["donor", "constituents", "getting-started", "daily-task"],
    estimatedReadTime: "4 min",
    difficulty: "beginner",
    role: "staff",
    images: [{ id: "img-donor-add-1", url: GUIDE_IMAGE, alt: "Donor CRM add constituent form", caption: "Add constituent form overview." }],
    walkthroughSteps: [
      { id: "dacs-1", title: "Open Constituents", instruction: "From the sidebar, click Constituents.", targetRoute: "/constituents", order: 1 },
      { id: "dacs-2", title: "Create Record", instruction: "Click Add Constituent and enter profile details.", order: 2 },
      { id: "dacs-3", title: "Save", instruction: "Save and confirm the new profile appears in the list.", order: 3 },
    ],
    relatedArticles: ["help-donor-import-csv", "help-donor-livecom"],
    lastUpdated: "2026-05-11",
    lastReviewed: "2026-05-11",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-donor-import-csv",
    title: "Import Donor Data From CSV",
    slug: "donor-import-csv",
    crmScope: "donor",
    category: "Imports & Exports",
    summary: "Upload CSV, map fields, validate required values, and review duplicate merge suggestions safely.",
    body: "Use Data Tools import flow in this order: Upload, Preview, Map Fields, Validate, Duplicate Review, Confirm Import, Review Results.",
    tags: ["donor", "import", "csv", "data-quality", "duplicates"],
    estimatedReadTime: "7 min",
    difficulty: "intermediate",
    role: "admin",
    walkthroughSteps: [
      { id: "dic-1", title: "Open Data Tools", instruction: "Navigate to Data Tools and choose import.", targetRoute: "/data-tools", order: 1 },
      { id: "dic-2", title: "Map Fields", instruction: "Map incoming columns to CRM fields and fix warnings.", order: 2 },
      { id: "dic-3", title: "Review Duplicates", instruction: "Confirm merge suggestions before import confirmation.", order: 3 },
    ],
    relatedArticles: ["help-global-permissions", "help-donor-add-constituent"],
    lastUpdated: "2026-05-11",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-donor-site-embeds",
    title: "Configure Site Embeds And Header Code Injection",
    slug: "donor-site-embeds",
    crmScope: "donor",
    category: "Website Embeds",
    summary: "Generate secure tokenized snippets, configure allow-listed domains, and test public loader health.",
    body: "Use Settings > Site Embeds to manage website connection metadata, LiveCom launcher settings, and script health checks. Install generated head or footer snippets only.",
    tags: ["site-embeds", "header-code", "footer-code", "livecom", "campaign-meter"],
    estimatedReadTime: "6 min",
    difficulty: "intermediate",
    role: "admin",
    images: [{ id: "img-site-embed-1", url: GUIDE_IMAGE, alt: "Site embeds manager", caption: "Website connection and snippet controls." }],
    walkthroughSteps: [
      { id: "dse-1", title: "Open Site Embeds", instruction: "Go to Settings and open Site Embeds.", targetRoute: "/settings/site-embeds", order: 1 },
      { id: "dse-2", title: "Set Domains", instruction: "Set primary and allowed domains for secure script execution.", order: 2 },
      { id: "dse-3", title: "Install Snippet", instruction: "Copy generated head or footer snippet into your website template.", order: 3 },
      { id: "dse-4", title: "Run Connection Test", instruction: "Use Test Connection to verify ping and allow-list status.", order: 4 },
    ],
    relatedArticles: ["help-donor-livecom"],
    lastUpdated: "2026-05-11",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-donor-livecom",
    title: "Use LiveCom For Website Conversations",
    slug: "donor-livecom-workspace",
    crmScope: "donor",
    category: "Communication",
    summary: "Capture website messages in LiveCom and convert interactions into follow-up tasks.",
    body: "LiveCom centralizes website chat and interaction updates. Track status, assign ownership, and connect interactions to constituent timelines.",
    tags: ["livecom", "communication", "inbox", "website-chat"],
    estimatedReadTime: "5 min",
    difficulty: "beginner",
    role: "staff",
    relatedArticles: ["help-donor-site-embeds"],
    lastUpdated: "2026-05-11",
    status: "published",
    featureReadiness: "Partially Working",
  },
  {
    id: "help-events-create-event",
    title: "Create And Activate An Event Workspace",
    slug: "events-create-event",
    crmScope: "events",
    category: "Getting Started",
    summary: "Create an event record, choose it in workspace selector, and open scoped operations tools.",
    body: "Events CRM uses event-first navigation. Start in Events registry, then choose your event from Workspace Selector before opening scoped tools.",
    tags: ["events", "workspace-selector", "event-scoped"],
    estimatedReadTime: "5 min",
    difficulty: "beginner",
    role: "staff",
    walkthroughSteps: [
      { id: "ece-1", title: "Create Event", instruction: "Open Events and create your event profile.", targetRoute: "/events/events", order: 1 },
      { id: "ece-2", title: "Select Workspace", instruction: "Open Workspace Selector and choose active event.", targetRoute: "/events/workspace", order: 2 },
      { id: "ece-3", title: "Open Scoped Tool", instruction: "Navigate to guests, tables, or check-in from selected event context.", order: 3 },
    ],
    relatedArticles: ["help-events-seating", "help-events-checkin"],
    lastUpdated: "2026-05-11",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-events-seating",
    title: "Manage Tables And Seating Assignments",
    slug: "events-table-seating",
    crmScope: "events",
    category: "Events",
    summary: "Build table layouts, assign guests, and monitor open seats before event day.",
    body: "Use Tables to set capacities, sponsor hosts, and assignments. Review over-capacity warnings and unassigned guests each day before check-in.",
    tags: ["events", "table-seating", "guests", "capacity"],
    estimatedReadTime: "6 min",
    difficulty: "intermediate",
    role: "staff",
    relatedArticles: ["help-events-checkin"],
    lastUpdated: "2026-05-11",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-events-checkin",
    title: "Run Event Check-In Operations",
    slug: "events-check-in-guide",
    crmScope: "events",
    category: "Daily Tasks",
    summary: "Use check-in workflows to process arrivals and track live attendance status.",
    body: "Open Check-In from an event-scoped route. Search guest roster, validate ticket status, and complete check-in actions in real time.",
    tags: ["events", "check-in", "guests", "operations"],
    estimatedReadTime: "4 min",
    difficulty: "beginner",
    role: "volunteer",
    lastUpdated: "2026-05-11",
    status: "published",
    featureReadiness: "Partially Working",
  },
  {
    id: "help-compassion-add-client",
    title: "Add A Client In Compassion CRM",
    slug: "compassion-add-client",
    crmScope: "compassion",
    category: "Clients",
    summary: "Create a new client profile with privacy-aware intake details and status tracking.",
    body: "Use Clients list to add a new profile. Keep sensitive fields protected and confirm intake timeline status.",
    tags: ["compassion", "clients", "intake", "privacy"],
    estimatedReadTime: "5 min",
    difficulty: "beginner",
    role: "staff",
    relatedArticles: ["help-compassion-appointments", "help-compassion-import"],
    lastUpdated: "2026-05-11",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-compassion-appointments",
    title: "Schedule And Manage Appointments",
    slug: "compassion-appointments-workspace",
    crmScope: "compassion",
    category: "Appointments",
    summary: "Use calendar and list views to schedule, reschedule, and complete appointments safely.",
    body: "Appointments workspace supports drag-drop scheduling, conflict detection, and quick status updates. Confirm client and staff assignment before saving.",
    tags: ["compassion", "appointments", "calendar", "rescheduling"],
    estimatedReadTime: "7 min",
    difficulty: "intermediate",
    role: "staff",
    walkthroughSteps: [
      { id: "caw-1", title: "Open Appointments", instruction: "Navigate to Compassion Appointments workspace.", targetRoute: "/compassion/appointments", order: 1 },
      { id: "caw-2", title: "Create Appointment", instruction: "Use Schedule Appointment button and complete required fields.", order: 2 },
      { id: "caw-3", title: "Confirm Calendar", instruction: "Verify event placement and status in calendar/list views.", order: 3 },
    ],
    relatedArticles: ["help-compassion-add-client"],
    lastUpdated: "2026-05-11",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-compassion-import",
    title: "Import Clients Safely",
    slug: "compassion-client-import",
    crmScope: "compassion",
    category: "Imports & Exports",
    summary: "Import client CSV files with validation guards for sensitive data boundaries.",
    body: "Compassion imports run strict validation and strip restricted identifiers. Use preview, mapping, validation, and duplicate review before commit.",
    tags: ["compassion", "import", "clients", "privacy", "validation"],
    estimatedReadTime: "6 min",
    difficulty: "intermediate",
    role: "admin",
    lastUpdated: "2026-05-11",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-global-login",
    title: "Get Started With OyamaCRM",
    slug: "global-getting-started",
    crmScope: "global",
    category: "Getting Started",
    summary: "Learn module switching, dashboard basics, and where to find key workspace tools.",
    body: "After login, use module switcher in TopBar to move between Donor, Events, and Compassion workspaces. Use Help from any module to get scoped guidance.",
    tags: ["global", "getting-started", "module-switcher", "dashboard"],
    estimatedReadTime: "3 min",
    difficulty: "beginner",
    role: "all",
    relatedArticles: ["help-global-permissions"],
    lastUpdated: "2026-05-11",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-global-permissions",
    title: "Understand Roles, Permissions, And Feature Readiness",
    slug: "global-permissions-and-readiness",
    crmScope: "global",
    category: "Security & Permissions",
    summary: "Review access boundaries and how feature readiness labels impact staff expectations.",
    body: "Roles control what each user can view and edit. Help articles may include feature readiness labels: Working, Partially Working, Demo Only, Broken, Not Implemented.",
    tags: ["global", "permissions", "security", "feature-readiness"],
    estimatedReadTime: "5 min",
    difficulty: "intermediate",
    role: "admin",
    lastUpdated: "2026-05-11",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-global-steward-ai",
    title: "Use Steward AI With Official Help Sources",
    slug: "global-steward-ai-help",
    crmScope: "global",
    category: "Steward AI",
    summary: "Use Steward AI for guidance while relying on published Help App content as trusted documentation.",
    body: "Steward AI can later consume Help App content for grounded responses. For now, use Help guides directly for confirmed workflows and current feature status.",
    tags: ["global", "steward-ai", "rag", "guidance"],
    estimatedReadTime: "4 min",
    difficulty: "intermediate",
    role: "all",
    lastUpdated: "2026-05-11",
    status: "published",
    featureReadiness: "Partially Working",
  },
  {
    id: "help-donor-record-donation",
    title: "Record A Donation In Donor CRM",
    slug: "donor-record-donation",
    crmScope: "donor",
    category: "Daily Tasks",
    summary: "Enter one-time gifts with designation, payment method, and acknowledgment settings.",
    body: "Open Donations, create a new donation, verify constituent, amount, designation, and payment method, then save and confirm receipt/acknowledgment status.",
    tags: ["donor", "donations", "gift-entry", "daily-task"],
    estimatedReadTime: "5 min",
    difficulty: "beginner",
    role: "staff",
    walkthroughSteps: [
      { id: "drd-1", title: "Open Donations", instruction: "Go to Donations from the sidebar.", targetRoute: "/donations", order: 1 },
      { id: "drd-2", title: "Create Donation", instruction: "Click New Donation and complete required fields.", order: 2 },
      { id: "drd-3", title: "Confirm Timeline", instruction: "Verify the donation appears in donor history.", order: 3 },
    ],
    relatedArticles: ["help-donor-add-constituent", "help-donor-recurring-gifts"],
    lastUpdated: "2026-05-16",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-donor-recurring-gifts",
    title: "Set Up Recurring Gifts",
    slug: "donor-recurring-gifts",
    crmScope: "donor",
    category: "Donations",
    summary: "Configure recurring schedules and monitor active, paused, and failed recurring gifts.",
    body: "Create recurring donation plans from donor or donation workflows, set interval and start date, and monitor recurring health indicators for failed payments.",
    tags: ["donor", "recurring", "donations", "stewardship"],
    estimatedReadTime: "6 min",
    difficulty: "intermediate",
    role: "staff",
    relatedArticles: ["help-donor-record-donation"],
    lastUpdated: "2026-05-16",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-donor-send-email-campaign",
    title: "Build And Send A Donor Email Campaign",
    slug: "donor-send-email-campaign",
    crmScope: "donor",
    category: "Communication",
    summary: "Create draft-first campaigns, run test sends, and launch with compliance checks.",
    body: "Use Communications to create a draft campaign, verify audience and compliance tokens, run send-test, then send now or schedule once approved.",
    tags: ["communications", "email", "campaign", "draft-first"],
    estimatedReadTime: "8 min",
    difficulty: "intermediate",
    role: "staff",
    walkthroughSteps: [
      { id: "dsec-1", title: "Open Communications", instruction: "Navigate to Communications workspace.", targetRoute: "/communications", order: 1 },
      { id: "dsec-2", title: "Create Campaign", instruction: "Set audience, subject, and content in draft mode.", order: 2 },
      { id: "dsec-3", title: "Test And Launch", instruction: "Run send-test and then send or schedule.", order: 3 },
    ],
    relatedArticles: ["help-global-email-provider-setup", "help-donor-manage-preferences"],
    lastUpdated: "2026-05-16",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-donor-manage-preferences",
    title: "Manage Donor Email Preferences And Unsubscribes",
    slug: "donor-email-preferences",
    crmScope: "donor",
    category: "Communication",
    summary: "Handle opt-outs, category preferences, and suppression-safe sending behavior.",
    body: "Before outreach, verify do-not-contact flags and email preference categories. Respect unsubscribe settings and never force-send suppressed recipients.",
    tags: ["email", "preferences", "unsubscribe", "compliance"],
    estimatedReadTime: "6 min",
    difficulty: "intermediate",
    role: "admin",
    relatedArticles: ["help-donor-send-email-campaign"],
    lastUpdated: "2026-05-16",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-donor-letters-print-queue",
    title: "Generate Letters And Manage Print Queue",
    slug: "donor-letters-print-queue",
    crmScope: "donor",
    category: "Letters & Printables",
    summary: "Move letters through review, print, and mail queue stages with clear ownership.",
    body: "Use Letters and Printables to draft or generate letters, review content, then move queue items through approved, printed, and mailed statuses.",
    tags: ["letters", "printables", "mail", "queue"],
    estimatedReadTime: "7 min",
    difficulty: "intermediate",
    role: "staff",
    walkthroughSteps: [
      { id: "dlpq-1", title: "Open Letters", instruction: "Go to Letters and Printables workspace.", targetRoute: "/letters-printables", order: 1 },
      { id: "dlpq-2", title: "Approve Draft", instruction: "Review generated content and approve for print.", order: 2 },
      { id: "dlpq-3", title: "Advance Queue", instruction: "Move queue items from printed to mailed.", order: 3 },
    ],
    relatedArticles: ["help-donor-send-email-campaign"],
    lastUpdated: "2026-05-16",
    status: "published",
    featureReadiness: "Partially Working",
  },
  {
    id: "help-donor-create-steward-task",
    title: "Create Stewardship Follow-Up Tasks",
    slug: "donor-stewardship-tasks",
    crmScope: "donor",
    category: "Task & Workflow",
    summary: "Assign donor follow-up tasks with due dates, priority, and relationship context.",
    body: "Use Tasks to create clear follow-up actions linked to constituents. Include due date, owner, and next-step details for stewardship continuity.",
    tags: ["tasks", "stewardship", "follow-up", "donor"],
    estimatedReadTime: "5 min",
    difficulty: "beginner",
    role: "staff",
    walkthroughSteps: [
      { id: "dst-1", title: "Open Tasks", instruction: "Navigate to Tasks workspace.", targetRoute: "/tasks", order: 1 },
      { id: "dst-2", title: "Create Task", instruction: "Set title, assignee, due date, and linked constituent.", order: 2 },
      { id: "dst-3", title: "Track Completion", instruction: "Update task status after outreach is complete.", order: 3 },
    ],
    relatedArticles: ["help-donor-add-constituent"],
    lastUpdated: "2026-05-16",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-donor-build-report",
    title: "Build A Donor Report And Export Results",
    slug: "donor-report-builder",
    crmScope: "donor",
    category: "Reporting",
    summary: "Create filtered report views for giving, retention, and stewardship progress.",
    body: "Open Reports, choose a report type or builder flow, apply filters, validate row counts, and export CSV/Excel for stakeholder review.",
    tags: ["reports", "analytics", "export", "retention"],
    estimatedReadTime: "7 min",
    difficulty: "intermediate",
    role: "admin",
    walkthroughSteps: [
      { id: "drb-1", title: "Open Reports", instruction: "Go to Reports workspace.", targetRoute: "/reports", order: 1 },
      { id: "drb-2", title: "Apply Filters", instruction: "Filter by date range, campaign, or designation.", order: 2 },
      { id: "drb-3", title: "Export", instruction: "Export data after validating totals.", order: 3 },
    ],
    relatedArticles: ["help-global-permissions"],
    lastUpdated: "2026-05-16",
    status: "published",
    featureReadiness: "Partially Working",
  },
  {
    id: "help-donor-grants-workspace",
    title: "Use The Grants Workspace",
    slug: "donor-grants-workspace",
    crmScope: "donor",
    category: "Grants",
    summary: "Track grant research, requirements, deadlines, and writing tasks without mixing donation ledger data.",
    body: "Use Grants as opportunity and writing workflow space. Record awarded funds through donation handoff flow only when money is received.",
    tags: ["grants", "deadlines", "writing", "research"],
    estimatedReadTime: "6 min",
    difficulty: "intermediate",
    role: "staff",
    walkthroughSteps: [
      { id: "dgw-1", title: "Open Grants", instruction: "Navigate to Grants workspace.", targetRoute: "/grants", order: 1 },
      { id: "dgw-2", title: "Add Opportunity", instruction: "Create funder opportunity with requirements and due dates.", order: 2 },
      { id: "dgw-3", title: "Assign Writing Tasks", instruction: "Create tasks for drafting and review deadlines.", order: 3 },
    ],
    lastUpdated: "2026-05-16",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-donor-quickbooks-queue",
    title: "Queue Donations For QuickBooks Sync",
    slug: "donor-quickbooks-sync-queue",
    crmScope: "donor",
    category: "Integrations",
    summary: "Use opt-in queue-based QuickBooks sync with manual review before sync actions.",
    body: "Enable QuickBooks plugin, opt-in donation queue entries, and run manual sync. Failed rows can be edited and retried; synced rows remain immutable.",
    tags: ["quickbooks", "integrations", "queue", "finance"],
    estimatedReadTime: "8 min",
    difficulty: "intermediate",
    role: "admin",
    walkthroughSteps: [
      { id: "dqb-1", title: "Enable Plugin", instruction: "Open Settings > Plugins and enable QuickBooks.", targetRoute: "/settings/plugins", order: 1 },
      { id: "dqb-2", title: "Open QB Queue", instruction: "Open QuickBooks Sync workspace.", targetRoute: "/quickbooks-sync", order: 2 },
      { id: "dqb-3", title: "Run Manual Sync", instruction: "Sync individual rows or sync-all after review.", order: 3 },
    ],
    lastUpdated: "2026-05-16",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-events-register-guests",
    title: "Register Guests For An Event",
    slug: "events-register-guests",
    crmScope: "events",
    category: "Events",
    summary: "Create guest records, assign ticket types, and verify RSVP/payment status before event day.",
    body: "Use event-scoped guest tools to add individual or batch guests and keep RSVP and payment status current for check-in readiness.",
    tags: ["events", "guests", "registration", "rsvp"],
    estimatedReadTime: "6 min",
    difficulty: "beginner",
    role: "staff",
    walkthroughSteps: [
      { id: "erg-1", title: "Open Event Workspace", instruction: "Select active event from workspace selector.", targetRoute: "/events/workspace", order: 1 },
      { id: "erg-2", title: "Add Guests", instruction: "Use guest registration flow to add attendees.", order: 2 },
      { id: "erg-3", title: "Verify Status", instruction: "Confirm RSVP and payment status columns are complete.", order: 3 },
    ],
    relatedArticles: ["help-events-checkin"],
    lastUpdated: "2026-05-16",
    status: "published",
    featureReadiness: "Partially Working",
  },
  {
    id: "help-events-page-builder",
    title: "Create Event Pages In Events Page Builder",
    slug: "events-page-builder",
    crmScope: "events",
    category: "Events",
    summary: "Use page builder for event landing pages and registration messaging workflows.",
    body: "Open Events Page Builder to create event pages, configure sections, and validate links before publishing.",
    tags: ["events", "page-builder", "website", "registration"],
    estimatedReadTime: "6 min",
    difficulty: "intermediate",
    role: "staff",
    walkthroughSteps: [
      { id: "epb-1", title: "Open Page Builder", instruction: "Navigate to Events Page Builder.", targetRoute: "/events/page-builder", order: 1 },
      { id: "epb-2", title: "Build Sections", instruction: "Add event details, schedule, and call-to-action content.", order: 2 },
      { id: "epb-3", title: "Preview", instruction: "Preview page before publish handoff.", order: 3 },
    ],
    lastUpdated: "2026-05-16",
    status: "published",
    featureReadiness: "Partially Working",
  },
  {
    id: "help-events-reports",
    title: "Run Cross-Event Reports",
    slug: "events-cross-event-reports",
    crmScope: "events",
    category: "Reporting",
    summary: "Compare attendance, revenue, and check-in metrics across multiple events.",
    body: "Use global Events Reports for cross-event analysis and trend tracking. Keep event-scoped tools for single-event operations only.",
    tags: ["events", "reports", "attendance", "revenue"],
    estimatedReadTime: "5 min",
    difficulty: "intermediate",
    role: "admin",
    walkthroughSteps: [
      { id: "eer-1", title: "Open Reports", instruction: "Navigate to Events Reports.", targetRoute: "/events/reports", order: 1 },
      { id: "eer-2", title: "Select Date Range", instruction: "Apply date/event filters for the comparison window.", order: 2 },
      { id: "eer-3", title: "Export", instruction: "Export summarized report views when needed.", order: 3 },
    ],
    relatedArticles: ["help-events-create-event"],
    lastUpdated: "2026-05-16",
    status: "published",
    featureReadiness: "Partially Working",
  },
  {
    id: "help-compassion-open-case",
    title: "Open A New Compassion Case",
    slug: "compassion-open-case",
    crmScope: "compassion",
    category: "Cases",
    summary: "Create a case linked to a client and track case stage safely within client boundaries.",
    body: "Use Cases workspace to open a new case, assign owner, and set initial status. Keep all service records scoped to the linked client profile.",
    tags: ["compassion", "cases", "client-scope", "workflow"],
    estimatedReadTime: "6 min",
    difficulty: "beginner",
    role: "staff",
    walkthroughSteps: [
      { id: "coc-1", title: "Open Cases", instruction: "Navigate to Compassion Cases.", targetRoute: "/compassion/cases", order: 1 },
      { id: "coc-2", title: "Create Case", instruction: "Select client, owner, and initial case details.", order: 2 },
      { id: "coc-3", title: "Verify Client Scope", instruction: "Confirm case appears in the client workspace timeline.", order: 3 },
    ],
    relatedArticles: ["help-compassion-add-client"],
    lastUpdated: "2026-05-16",
    status: "published",
    featureReadiness: "Partially Working",
  },
  {
    id: "help-compassion-follow-up-tasks",
    title: "Manage Compassion Follow-Up Tasks",
    slug: "compassion-follow-up-tasks",
    crmScope: "compassion",
    category: "Task & Workflow",
    summary: "Assign follow-up actions for client appointments, referrals, and case reviews.",
    body: "Use Tasks and Follow Ups in Compassion to assign ownership and due dates. Keep task notes privacy-safe and client-specific.",
    tags: ["compassion", "tasks", "follow-ups", "case-management"],
    estimatedReadTime: "5 min",
    difficulty: "beginner",
    role: "staff",
    walkthroughSteps: [
      { id: "cft-1", title: "Open Follow Ups", instruction: "Navigate to Follow Ups workspace.", targetRoute: "/compassion/follow-ups", order: 1 },
      { id: "cft-2", title: "Create Task", instruction: "Add task title, due date, and assigned staff member.", order: 2 },
      { id: "cft-3", title: "Close Task", instruction: "Mark complete when outreach is finished.", order: 3 },
    ],
    relatedArticles: ["help-compassion-appointments"],
    lastUpdated: "2026-05-16",
    status: "published",
    featureReadiness: "Partially Working",
  },
  {
    id: "help-compassion-public-scheduling-widget",
    title: "Configure Public Scheduling Widget",
    slug: "compassion-public-scheduling-widget",
    crmScope: "compassion",
    category: "Appointments",
    summary: "Publish appointment slots using server-generated availability and submit-time validation.",
    body: "Configure appointment widget policy, publish tokenized embed, and verify slot generation endpoint before sharing public links.",
    tags: ["compassion", "appointments", "widget", "public-scheduling"],
    estimatedReadTime: "7 min",
    difficulty: "advanced",
    role: "admin",
    walkthroughSteps: [
      { id: "cpsw-1", title: "Open Appointment Settings", instruction: "Configure scheduling policy and availability windows.", targetRoute: "/compassion/appointments", order: 1 },
      { id: "cpsw-2", title: "Publish Widget", instruction: "Generate widget token and embed snippet.", order: 2 },
      { id: "cpsw-3", title: "Validate Slots", instruction: "Confirm public slot endpoint returns expected results.", order: 3 },
    ],
    relatedArticles: ["help-compassion-appointments"],
    lastUpdated: "2026-05-16",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-global-email-provider-setup",
    title: "Set Up System Email Provider",
    slug: "global-email-provider-setup",
    crmScope: "global",
    category: "System Setup",
    summary: "Configure standard SMTP, Microsoft 365 SMTP, or Microsoft Graph provider settings.",
    body: "Open Organization Settings, choose outbound provider, complete credentials, run provider test send, and save before launching campaigns.",
    tags: ["smtp", "microsoft-graph", "email", "settings"],
    estimatedReadTime: "8 min",
    difficulty: "intermediate",
    role: "admin",
    walkthroughSteps: [
      { id: "ges-1", title: "Open Organization Settings", instruction: "Navigate to Settings > Organization.", targetRoute: "/settings/organization", order: 1 },
      { id: "ges-2", title: "Choose Provider", instruction: "Select SMTP, Microsoft 365 SMTP, or Microsoft Graph.", order: 2 },
      { id: "ges-3", title: "Run Provider Test", instruction: "Send provider test email and confirm success.", order: 3 },
    ],
    relatedArticles: ["help-donor-send-email-campaign"],
    lastUpdated: "2026-05-16",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-global-microsoft-graph-connect",
    title: "Connect Microsoft Graph For Outbound Email",
    slug: "global-microsoft-graph-connect",
    crmScope: "global",
    category: "System Setup",
    summary: "Complete OAuth connect flow and verify Graph send permissions for production email.",
    body: "Save tenant/client credentials, start OAuth auth-uri flow, complete callback connect, and run provider test with Graph mode.",
    tags: ["microsoft-graph", "oauth", "mail-send", "connectors"],
    estimatedReadTime: "9 min",
    difficulty: "advanced",
    role: "admin",
    walkthroughSteps: [
      { id: "gmgc-1", title: "Save Graph Credentials", instruction: "Enter tenant ID, client ID, and secret.", targetRoute: "/settings/organization", order: 1 },
      { id: "gmgc-2", title: "Connect OAuth", instruction: "Run Connect Microsoft Graph and complete consent.", order: 2 },
      { id: "gmgc-3", title: "Verify Provider Test", instruction: "Run provider test and confirm Graph mode response.", order: 3 },
    ],
    relatedArticles: ["help-global-email-provider-setup"],
    lastUpdated: "2026-05-16",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-global-troubleshoot-help-search",
    title: "Troubleshoot Help Search And Agent Suggestions",
    slug: "global-help-search-troubleshooting",
    crmScope: "global",
    category: "Troubleshooting",
    summary: "Use scoped filters, route context, and keyword matching to find the right guide quickly.",
    body: "When results look thin, remove restrictive filters, switch scope, and use practical terms like import, check-in, donation, appointment, or report.",
    tags: ["help", "search", "troubleshooting", "agent"],
    estimatedReadTime: "4 min",
    difficulty: "beginner",
    role: "all",
    lastUpdated: "2026-05-16",
    status: "published",
    featureReadiness: "Working",
  },
  {
    id: "help-global-steward-help-mode",
    title: "Use Steward Help Mode With Guide Links",
    slug: "global-steward-help-mode",
    crmScope: "global",
    category: "Steward AI",
    summary: "Ask how-to questions in Steward and use linked Help guides for route-by-route execution.",
    body: "Switch Steward to Help mode, ask outcome-oriented questions, then open linked Help guides and route actions directly from the response.",
    tags: ["steward-ai", "help-mode", "guides", "workflow"],
    estimatedReadTime: "4 min",
    difficulty: "beginner",
    role: "all",
    relatedArticles: ["help-global-steward-ai"],
    lastUpdated: "2026-05-16",
    status: "published",
    featureReadiness: "Working",
  },

  // ── Donor CRM: Campaigns ───────────────────────────────────────────────────
  {
    id: "help-donor-campaigns",
    title: "Create And Manage Fundraising Campaigns",
    slug: "donor-campaigns",
    crmScope: "donor",
    category: "Campaigns",
    summary: "Create campaigns with goals, timelines, and designations, then track progress against targets.",
    body: "Open Campaigns, create a new campaign with name, goal amount, start and end dates. Assign a designation fund, mark active, and track revenue progress in the campaign detail view.",
    tags: ["campaigns", "fundraising", "goals", "designations", "donor"],
    estimatedReadTime: "6 min",
    difficulty: "intermediate",
    role: "staff",
    walkthroughSteps: [
      { id: "dc-1", title: "Open Campaigns", instruction: "Navigate to Campaigns from the sidebar.", targetRoute: "/campaigns", order: 1 },
      { id: "dc-2", title: "Create Campaign", instruction: "Click New Campaign and enter name, goal, and dates.", order: 2 },
      { id: "dc-3", title: "Track Progress", instruction: "View campaign detail to monitor revenue vs goal.", order: 3 },
    ],
    relatedArticles: ["help-donor-record-donation", "help-donor-build-report"],
    lastUpdated: "2026-05-18",
    status: "published",
    featureReadiness: "Working",
  },

  // ── Donor CRM: Constituent profile ────────────────────────────────────────
  {
    id: "help-donor-view-constituent-profile",
    title: "Navigate A Constituent Profile And Timeline",
    slug: "donor-view-constituent-profile",
    crmScope: "donor",
    category: "Daily Tasks",
    summary: "View giving history, tasks, notes, tags, and communication activity from one unified profile.",
    body: "Open a constituent profile from the Constituents list. Navigate the timeline to see donations, tasks, emails, letters, and engagement notes in chronological order. Use tabs to switch between giving history, notes, and contact info.",
    tags: ["donor", "constituents", "profile", "timeline", "activity"],
    estimatedReadTime: "5 min",
    difficulty: "beginner",
    role: "staff",
    walkthroughSteps: [
      { id: "dvcp-1", title: "Open Constituent List", instruction: "Go to Constituents from the sidebar.", targetRoute: "/constituents", order: 1 },
      { id: "dvcp-2", title: "View Profile", instruction: "Click a constituent name to open their full profile.", order: 2 },
      { id: "dvcp-3", title: "Browse Timeline", instruction: "Scroll the activity timeline and switch tabs for giving, notes, and communication history.", order: 3 },
    ],
    relatedArticles: ["help-donor-add-constituent", "help-donor-record-donation"],
    lastUpdated: "2026-05-18",
    status: "published",
    featureReadiness: "Working",
  },

  // ── Donor CRM: Steward Paths setup ────────────────────────────────────────
  {
    id: "help-donor-steward-paths-setup",
    title: "Set Up A Steward Paths Engagement Sequence",
    slug: "donor-steward-paths-setup",
    crmScope: "donor",
    category: "Steward Paths",
    summary: "Build multi-step stewardship sequences that automatically schedule tasks, letters, and status updates.",
    body: "Open Steward Paths, create a new path with steps. Choose step types: tasks, emails, letters, status changes, or branch conditions. Assign audience and activate the path. Paths run step-by-step, with branch conditions deciding next action based on constituent data.",
    tags: ["steward", "stewardship", "sequence", "engagement", "paths"],
    estimatedReadTime: "10 min",
    difficulty: "advanced",
    role: "admin",
    walkthroughSteps: [
      { id: "dsps-1", title: "Open Steward Paths", instruction: "Navigate to Steward Paths workspace.", targetRoute: "/steward-paths", order: 1 },
      { id: "dsps-2", title: "Create Path", instruction: "Click New Path, name it, and add steps one by one.", order: 2 },
      { id: "dsps-3", title: "Add Step Types", instruction: "Choose task, email, letter, status change, or branch for each step.", order: 3 },
      { id: "dsps-4", title: "Set Audience", instruction: "Assign the path to a segment or individual constituent.", order: 4 },
      { id: "dsps-5", title: "Activate Path", instruction: "Set path to active and confirm sequence will advance on schedule.", order: 5 },
    ],
    relatedArticles: ["help-donor-stewardship-tasks", "help-donor-send-email-campaign"],
    lastUpdated: "2026-05-18",
    status: "published",
    featureReadiness: "Working",
  },

  // ── Donor CRM: Contacts Manager ───────────────────────────────────────────
  {
    id: "help-donor-contacts-manager",
    title: "Build Audience Lists With Contacts Manager",
    slug: "donor-contacts-manager",
    crmScope: "donor",
    category: "Outreach",
    summary: "Select and segment constituents into reusable audience lists for campaigns, letters, and email sends.",
    body: "Use Contacts Manager to search, filter, and select constituents. Use the side-by-side list builder to compose audiences. Save named segments and load them into email or letter workflows. Bulk tag selected constituents for future segmentation.",
    tags: ["contacts", "segment", "audience", "list", "outreach", "email"],
    estimatedReadTime: "8 min",
    difficulty: "intermediate",
    role: "staff",
    walkthroughSteps: [
      { id: "dcm-1", title: "Open Contacts Manager", instruction: "Navigate to Contacts Manager from the sidebar.", targetRoute: "/contacts-manager", order: 1 },
      { id: "dcm-2", title: "Filter and Select", instruction: "Apply filters and use checkboxes to select constituent rows.", order: 2 },
      { id: "dcm-3", title: "Build Audience", instruction: "Add selected rows to the audience list builder on the right.", order: 3 },
      { id: "dcm-4", title: "Save Segment", instruction: "Name and save the audience list for reuse in email/letter sends.", order: 4 },
    ],
    relatedArticles: ["help-donor-send-email-campaign", "help-donor-letters-print-queue"],
    lastUpdated: "2026-05-18",
    status: "published",
    featureReadiness: "Working",
  },

  // ── Donor CRM: Pledge management ──────────────────────────────────────────
  {
    id: "help-donor-pledges",
    title: "Record And Track Pledge Commitments",
    slug: "donor-pledges",
    crmScope: "donor",
    category: "Donations",
    summary: "Create pledge records for commitments over time and track fulfillment against pledge totals.",
    body: "Pledges represent commitments to give over a period. Record the pledged amount and schedule, then record individual payments against the pledge. Track fulfillment percentage in the constituent profile and campaign views.",
    tags: ["donations", "pledge", "commitment", "recurring", "donor"],
    estimatedReadTime: "7 min",
    difficulty: "intermediate",
    role: "staff",
    relatedArticles: ["help-donor-record-donation", "help-donor-recurring-gifts"],
    lastUpdated: "2026-05-18",
    status: "published",
    featureReadiness: "Partially Working",
  },

  // ── Donor CRM: Retention analysis ─────────────────────────────────────────
  {
    id: "help-donor-retention-analysis",
    title: "Analyze Donor Retention Metrics",
    slug: "donor-retention-analysis",
    crmScope: "donor",
    category: "Reporting",
    summary: "Review year-over-year giving trends and identify lapsed or at-risk donors for re-engagement.",
    body: "Use the Reports workspace to run retention analysis. Filter by fiscal year to compare donors who gave in both current and prior year. Export lapsed donor lists for targeted re-engagement campaigns.",
    tags: ["retention", "analytics", "reports", "lapsed", "at-risk", "donor"],
    estimatedReadTime: "7 min",
    difficulty: "intermediate",
    role: "admin",
    relatedArticles: ["help-donor-build-report", "help-donor-campaigns"],
    lastUpdated: "2026-05-18",
    status: "published",
    featureReadiness: "Partially Working",
  },

  // ── Donor CRM: Volunteers ──────────────────────────────────────────────────
  {
    id: "help-donor-volunteers",
    title: "Track Volunteers In Donor CRM",
    slug: "donor-volunteers",
    crmScope: "donor",
    category: "Task & Workflow",
    summary: "Log volunteer hours, assign volunteer tasks, and link volunteer activity to constituent profiles.",
    body: "Use Volunteers workspace to add volunteer records, assign tasks with date and hours, and associate volunteer activity with constituent timelines. Track total volunteer hours per person and per campaign.",
    tags: ["volunteers", "tasks", "donor", "engagement"],
    estimatedReadTime: "6 min",
    difficulty: "beginner",
    role: "staff",
    walkthroughSteps: [
      { id: "dvol-1", title: "Open Volunteers", instruction: "Navigate to Volunteers from the sidebar.", targetRoute: "/volunteers", order: 1 },
      { id: "dvol-2", title: "Add Volunteer Record", instruction: "Link a constituent as a volunteer and log hours.", order: 2 },
      { id: "dvol-3", title: "Assign Tasks", instruction: "Assign volunteer tasks with due dates and completion tracking.", order: 3 },
    ],
    relatedArticles: ["help-donor-stewardship-tasks"],
    lastUpdated: "2026-05-18",
    status: "published",
    featureReadiness: "Partially Working",
  },

  // ── Donor CRM: Dashboard metrics ──────────────────────────────────────────
  {
    id: "help-donor-dashboard-metrics",
    title: "Understand The Donor CRM Dashboard",
    slug: "donor-dashboard-metrics",
    crmScope: "donor",
    category: "Getting Started",
    summary: "Interpret YTD giving, retention rate, campaign progress, and task overview widgets on the main dashboard.",
    body: "The Donor CRM dashboard shows year-to-date giving totals, donor retention percentage, campaign goal progress, overdue tasks, at-risk donors, and recent activity. Use widget controls to customize which panels appear.",
    tags: ["dashboard", "metrics", "analytics", "getting-started", "retention", "donor"],
    estimatedReadTime: "5 min",
    difficulty: "beginner",
    role: "all",
    relatedArticles: ["help-donor-retention-analysis", "help-donor-build-report"],
    lastUpdated: "2026-05-18",
    status: "published",
    featureReadiness: "Working",
  },

  // ── Donor CRM: Communications email templates ─────────────────────────────
  {
    id: "help-donor-email-builder",
    title: "Use The Email Campaign Builder",
    slug: "donor-email-builder",
    crmScope: "donor",
    category: "Communication",
    summary: "Build branded email campaigns with block library, canvas, and inspector in the studio workspace.",
    body: "Open the Email Builder from Communications. Use the block library on the left to drag content, image, button, and AI text blocks onto the canvas. Configure each block in the inspector on the right. Preview on mobile and desktop before saving.",
    tags: ["email", "builder", "campaign", "template", "communications"],
    estimatedReadTime: "9 min",
    difficulty: "intermediate",
    role: "staff",
    walkthroughSteps: [
      { id: "deb-1", title: "Open Email Builder", instruction: "Go to Communications and open or create a campaign.", targetRoute: "/communications", order: 1 },
      { id: "deb-2", title: "Add Blocks", instruction: "Drag blocks from the library onto the canvas.", order: 2 },
      { id: "deb-3", title: "Configure Block", instruction: "Click a block and edit it using the inspector panel.", order: 3 },
      { id: "deb-4", title: "Preview and Save", instruction: "Use preview to check mobile/desktop layout, then save draft.", order: 4 },
    ],
    relatedArticles: ["help-donor-send-email-campaign", "help-donor-manage-preferences"],
    lastUpdated: "2026-05-18",
    status: "published",
    featureReadiness: "Working",
  },

  // ── Donor CRM: Import donations ───────────────────────────────────────────
  {
    id: "help-donor-import-donations",
    title: "Import Historical Donation Data",
    slug: "donor-import-donations",
    crmScope: "donor",
    category: "Imports & Exports",
    summary: "Migrate donation history from spreadsheets using guided import with field mapping and validation.",
    body: "Use the Guided Import in Data Tools. Select 'Donation Records' import type, upload CSV, map donation amount/date/designation/method fields, validate required fields, and review before commit.",
    tags: ["import", "donations", "csv", "history", "data-quality"],
    estimatedReadTime: "8 min",
    difficulty: "intermediate",
    role: "admin",
    walkthroughSteps: [
      { id: "did-1", title: "Open Guided Import", instruction: "Go to Data Tools and select Guided Import.", targetRoute: "/data-tools/import", order: 1 },
      { id: "did-2", title: "Select Donation Type", instruction: "Choose Donation Records as import type.", order: 2 },
      { id: "did-3", title: "Map Fields", instruction: "Map amount, date, designations, and payment method columns.", order: 3 },
      { id: "did-4", title: "Validate and Commit", instruction: "Review validation warnings and confirm import.", order: 4 },
    ],
    relatedArticles: ["help-donor-import-csv", "help-donor-record-donation"],
    lastUpdated: "2026-05-18",
    status: "published",
    featureReadiness: "Partially Working",
  },

  // ── Events CRM: Sponsors ──────────────────────────────────────────────────
  {
    id: "help-events-sponsors",
    title: "Manage Event Sponsors And Sponsorship Packages",
    slug: "events-sponsors",
    crmScope: "events",
    category: "Events",
    summary: "Add sponsors, assign sponsorship packages with included seat counts, and link to table assignments.",
    body: "Use the Sponsors workspace within an event to add sponsor organizations, assign packages, and allocate seats. Sponsored tables are marked separately in the seating chart.",
    tags: ["sponsor", "events", "sponsorship", "tables", "packages"],
    estimatedReadTime: "6 min",
    difficulty: "intermediate",
    role: "staff",
    walkthroughSteps: [
      { id: "es-1", title: "Select Event", instruction: "Choose your event from Workspace Selector.", targetRoute: "/events/workspace", order: 1 },
      { id: "es-2", title: "Open Sponsors", instruction: "Navigate to Sponsors within the event tools.", order: 2 },
      { id: "es-3", title: "Add Sponsor", instruction: "Create sponsor record, choose package, and allocate seats.", order: 3 },
    ],
    relatedArticles: ["help-events-seating", "help-events-create-event"],
    lastUpdated: "2026-05-18",
    status: "published",
    featureReadiness: "Partially Working",
  },

  // ── Events CRM: Ticket types ──────────────────────────────────────────────
  {
    id: "help-events-tickets",
    title: "Configure Event Ticket Types",
    slug: "events-tickets",
    crmScope: "events",
    category: "Events",
    summary: "Define individual, table-of-N, comp, and sponsored ticket types with pricing and seat counts.",
    body: "Use event Tickets workspace to create ticket types. Set ticket name, price, seat count per ticket, and type (individual, table, comp, sponsored). Assign guest registrations to ticket types during registration.",
    tags: ["ticket", "events", "registration", "table", "pricing"],
    estimatedReadTime: "5 min",
    difficulty: "intermediate",
    role: "admin",
    relatedArticles: ["help-events-register-guests", "help-events-create-event"],
    lastUpdated: "2026-05-18",
    status: "published",
    featureReadiness: "Partially Working",
  },

  // ── Events CRM: Event overview dashboard ─────────────────────────────────
  {
    id: "help-events-overview-dashboard",
    title: "Read The Event Overview Dashboard",
    slug: "events-overview-dashboard",
    crmScope: "events",
    category: "Events",
    summary: "Monitor event-day readiness: check-in rate, RSVP counts, revenue, and seat fill percentages.",
    body: "The event overview dashboard shows live check-in progress, guest arrival rates, total revenue, outstanding payments, and table occupancy. Use it as your command center on event day.",
    tags: ["events", "dashboard", "check-in", "revenue", "attendance"],
    estimatedReadTime: "4 min",
    difficulty: "beginner",
    role: "staff",
    relatedArticles: ["help-events-checkin", "help-events-seating"],
    lastUpdated: "2026-05-18",
    status: "published",
    featureReadiness: "Partially Working",
  },

  // ── Compassion CRM: Assessments ───────────────────────────────────────────
  {
    id: "help-compassion-assessments",
    title: "Complete Client Assessments",
    slug: "compassion-assessments",
    crmScope: "compassion",
    category: "Clients",
    summary: "Record intake assessments, pregnancy tests, and needs evaluations within the client workspace.",
    body: "Open a client profile, navigate to Assessments. Complete structured intake assessments and record test results. All assessment data is scoped strictly to the selected client and is not visible across other client profiles.",
    tags: ["compassion", "assessment", "intake", "client", "privacy"],
    estimatedReadTime: "6 min",
    difficulty: "intermediate",
    role: "staff",
    walkthroughSteps: [
      { id: "ca-1", title: "Open Client Profile", instruction: "Navigate to Compassion Clients and select a client.", targetRoute: "/compassion/clients", order: 1 },
      { id: "ca-2", title: "Select Assessments Tab", instruction: "Open the Assessments section within the client workspace.", order: 2 },
      { id: "ca-3", title: "Complete Assessment", instruction: "Fill in assessment fields and save the record.", order: 3 },
    ],
    relatedArticles: ["help-compassion-add-client", "help-compassion-open-case"],
    lastUpdated: "2026-05-18",
    status: "published",
    featureReadiness: "Partially Working",
  },

  // ── Compassion CRM: Referrals ──────────────────────────────────────────────
  {
    id: "help-compassion-referrals",
    title: "Record Client Referrals",
    slug: "compassion-referrals",
    crmScope: "compassion",
    category: "Cases",
    summary: "Track external referrals made on behalf of a client with agency, contact, and follow-up details.",
    body: "Open the client profile, navigate to Referrals. Add the referral agency, contact, reason, and date. Set follow-up status and assign a staff owner. Referral records stay scoped to the client and link to the case timeline.",
    tags: ["compassion", "referral", "case", "client", "follow-up"],
    estimatedReadTime: "5 min",
    difficulty: "beginner",
    role: "staff",
    relatedArticles: ["help-compassion-open-case", "help-compassion-follow-up-tasks"],
    lastUpdated: "2026-05-18",
    status: "published",
    featureReadiness: "Partially Working",
  },

  // ── Compassion CRM: Reports ────────────────────────────────────────────────
  {
    id: "help-compassion-reports",
    title: "Run Compassion CRM Service Reports",
    slug: "compassion-reports",
    crmScope: "compassion",
    category: "Reporting",
    summary: "Generate service summary reports, appointment counts, and case status distributions.",
    body: "Use the Compassion Reports workspace to run appointment volume reports, active case counts, and service distribution summaries. Apply date and staff filters. Export data for grant reporting and compliance.",
    tags: ["compassion", "reports", "analytics", "appointments", "cases"],
    estimatedReadTime: "6 min",
    difficulty: "intermediate",
    role: "admin",
    relatedArticles: ["help-compassion-open-case", "help-compassion-appointments"],
    lastUpdated: "2026-05-18",
    status: "published",
    featureReadiness: "Partially Working",
  },

  // ── Compassion CRM: Material assistance ───────────────────────────────────
  {
    id: "help-compassion-material-assistance",
    title: "Record Material Assistance In Client Profiles",
    slug: "compassion-material-assistance",
    crmScope: "compassion",
    category: "Clients",
    summary: "Log boutique visits, resource items given, and in-kind assistance within the client profile.",
    body: "Open a client profile and navigate to the Material Assistance or Boutique section. Log each assistance session with date, items, and staff name. Cumulative totals are visible in the client overview and can be included in service reports.",
    tags: ["compassion", "material-assistance", "boutique", "client", "resources"],
    estimatedReadTime: "5 min",
    difficulty: "beginner",
    role: "staff",
    relatedArticles: ["help-compassion-add-client"],
    lastUpdated: "2026-05-18",
    status: "published",
    featureReadiness: "Not Implemented",
  },

  // ── Global: System settings overview ──────────────────────────────────────
  {
    id: "help-global-system-settings",
    title: "Navigate The Settings Workspace",
    slug: "global-system-settings",
    crmScope: "global",
    category: "System Setup",
    summary: "Overview of all settings sections: organization, email, security, integrations, and system info.",
    body: "Settings is organized into sections: Organization (name, logo, email provider), Security (audit logs, user roles), Integrations (QuickBooks, webhooks), and System (version info, runtime status). Admin role required for most sections.",
    tags: ["settings", "admin", "organization", "security", "getting-started"],
    estimatedReadTime: "5 min",
    difficulty: "beginner",
    role: "admin",
    relatedArticles: ["help-global-email-provider-setup", "help-global-permissions"],
    lastUpdated: "2026-05-18",
    status: "published",
    featureReadiness: "Working",
  },

  // ── Global: Organization settings ─────────────────────────────────────────
  {
    id: "help-global-org-settings",
    title: "Configure Organization Settings",
    slug: "global-org-settings",
    crmScope: "global",
    category: "System Setup",
    summary: "Set organization name, logo, timezone, fiscal year start, and outbound email provider.",
    body: "Open Settings > Organization to complete your organization profile. Set name, mailing address, default timezone, fiscal year start month, and outbound email provider. These values are used in reports, receipts, and system-generated messages.",
    tags: ["settings", "organization", "admin", "configure"],
    estimatedReadTime: "6 min",
    difficulty: "beginner",
    role: "admin",
    walkthroughSteps: [
      { id: "gos-1", title: "Open Organization Settings", instruction: "Navigate to Settings > Organization.", targetRoute: "/settings/organization", order: 1 },
      { id: "gos-2", title: "Complete Profile", instruction: "Enter organization name, address, and timezone.", order: 2 },
      { id: "gos-3", title: "Configure Email", instruction: "Select outbound email provider and test send.", order: 3 },
    ],
    relatedArticles: ["help-global-email-provider-setup"],
    lastUpdated: "2026-05-18",
    status: "published",
    featureReadiness: "Working",
  },

  // ── Global: Audit log ─────────────────────────────────────────────────────
  {
    id: "help-global-audit-log",
    title: "Review The System Audit Log",
    slug: "global-audit-log",
    crmScope: "global",
    category: "Security & Permissions",
    summary: "View a complete record of user actions, data changes, imports, merges, and admin operations.",
    body: "Audit logs are available in Settings > Security & Audit. Filter by user, action type, or date range. Logs are read-only and cannot be deleted. Use audit records for compliance reporting and troubleshooting unexpected changes.",
    tags: ["audit", "security", "log", "compliance", "admin"],
    estimatedReadTime: "5 min",
    difficulty: "intermediate",
    role: "admin",
    relatedArticles: ["help-global-permissions", "help-global-security-privacy"],
    lastUpdated: "2026-05-18",
    status: "published",
    featureReadiness: "Working",
  },

  // ── Global: User management ────────────────────────────────────────────────
  {
    id: "help-global-user-management",
    title: "Manage Users And Role Assignments",
    slug: "global-user-management",
    crmScope: "global",
    category: "Security & Permissions",
    summary: "Invite staff, assign roles (admin/staff/volunteer), and manage active account status.",
    body: "Open Settings > Security to manage platform users. Invite new staff by email and assign a role. Admin can edit roles, deactivate accounts, and reset passwords. Roles control which modules and tools each user can access.",
    tags: ["users", "roles", "admin", "security", "permissions"],
    estimatedReadTime: "6 min",
    difficulty: "intermediate",
    role: "admin",
    relatedArticles: ["help-global-permissions"],
    lastUpdated: "2026-05-18",
    status: "published",
    featureReadiness: "Partially Working",
  },

  // ── Global: Data export ───────────────────────────────────────────────────
  {
    id: "help-global-data-export",
    title: "Export Data From OyamaCRM",
    slug: "global-data-export",
    crmScope: "global",
    category: "Imports & Exports",
    summary: "Export constituents, donations, campaigns, and reports to CSV or Excel for external use.",
    body: "Most list views and reports include an Export button. Select the columns and date range you need, choose CSV or Excel format, and download. Sensitive client data exports require admin role and are privacy-filtered.",
    tags: ["export", "csv", "data", "report", "download"],
    estimatedReadTime: "5 min",
    difficulty: "beginner",
    role: "staff",
    relatedArticles: ["help-donor-build-report", "help-donor-import-csv"],
    lastUpdated: "2026-05-18",
    status: "published",
    featureReadiness: "Partially Working",
  },

  // ── Global: Security and privacy ──────────────────────────────────────────
  {
    id: "help-global-security-privacy",
    title: "Review Security And Privacy Settings",
    slug: "global-security-privacy",
    crmScope: "global",
    category: "Security & Permissions",
    summary: "Configure session timeouts, data privacy notices, and access control rules.",
    body: "Security settings are in Settings > Security. Configure session timeout duration, require two-factor for admin accounts, set data retention policies, and review active sessions.",
    tags: ["security", "privacy", "audit", "sessions", "admin"],
    estimatedReadTime: "6 min",
    difficulty: "advanced",
    role: "admin",
    relatedArticles: ["help-global-audit-log", "help-global-user-management"],
    lastUpdated: "2026-05-18",
    status: "published",
    featureReadiness: "Partially Working",
  },

  // ── Global: Notifications ─────────────────────────────────────────────────
  {
    id: "help-global-notifications",
    title: "Configure Notifications And Reminders",
    slug: "global-notifications",
    crmScope: "global",
    category: "System Setup",
    summary: "Set up overdue task reminders, campaign milestone alerts, and system health notifications.",
    body: "Notifications appear in the TopBar notification panel. Task reminders are triggered by due date proximity. Campaign milestone alerts fire when goals are reached. System health alerts flag email provider failures or import errors.",
    tags: ["notifications", "reminders", "alerts", "tasks", "system"],
    estimatedReadTime: "5 min",
    difficulty: "beginner",
    role: "all",
    relatedArticles: ["help-donor-stewardship-tasks"],
    lastUpdated: "2026-05-18",
    status: "published",
    featureReadiness: "Partially Working",
  },

  // ── Global: Setup wizard ──────────────────────────────────────────────────
  {
    id: "help-global-setup-wizard",
    title: "Complete The First-Run Setup Wizard",
    slug: "global-setup-wizard",
    crmScope: "global",
    category: "Getting Started",
    summary: "Walk through initial platform setup: organization profile, first admin account, and email provider.",
    body: "On first login you are redirected to the Setup wizard. Complete organization name and address, create the admin account password, configure outbound email, and confirm to begin using the platform.",
    tags: ["setup", "getting-started", "configuration", "onboarding"],
    estimatedReadTime: "5 min",
    difficulty: "beginner",
    role: "admin",
    walkthroughSteps: [
      { id: "gsw-1", title: "Organization Profile", instruction: "Enter organization name, address, and timezone.", order: 1 },
      { id: "gsw-2", title: "Admin Account", instruction: "Set admin email and secure password.", order: 2 },
      { id: "gsw-3", title: "Email Provider", instruction: "Configure SMTP or Microsoft Graph for outbound email.", order: 3 },
      { id: "gsw-4", title: "Confirm Setup", instruction: "Review settings and complete setup to access dashboard.", order: 4 },
    ],
    relatedArticles: ["help-global-getting-started", "help-global-email-provider-setup"],
    lastUpdated: "2026-05-18",
    status: "published",
    featureReadiness: "Working",
  },

  // ── Global: Webmaster basics ──────────────────────────────────────────────
  {
    id: "help-global-webmaster",
    title: "Use OyamaWebMaster For Website Management",
    slug: "global-webmaster",
    crmScope: "global",
    category: "Webmaster",
    summary: "Manage website pages, publishing workflows, and CRM-connected web content from one workspace.",
    body: "OyamaWebMaster is the platform website command center. Create site records, manage page content, and connect pages to CRM modules. Publishing workflows are review-first and non-destructive by default.",
    tags: ["webmaster", "website", "pages", "publishing"],
    estimatedReadTime: "6 min",
    difficulty: "intermediate",
    role: "admin",
    relatedArticles: ["help-donor-site-embeds"],
    lastUpdated: "2026-05-18",
    status: "published",
    featureReadiness: "Partially Working",
  },

  // ── Global: Troubleshoot connectivity ────────────────────────────────────
  {
    id: "help-global-troubleshoot-connectivity",
    title: "Troubleshoot Email Provider And API Connectivity",
    slug: "global-troubleshoot-connectivity",
    crmScope: "global",
    category: "Troubleshooting",
    summary: "Diagnose failed email sends, SMTP errors, Microsoft Graph auth issues, and API connection failures.",
    body: "When email sends fail, check Settings > Organization > Email Provider. Run the provider test send. For SMTP issues, verify credentials and port/TLS settings. For Microsoft Graph, confirm OAuth token is still valid and re-authorize if needed.",
    tags: ["troubleshooting", "smtp", "microsoft-graph", "email", "connectivity"],
    estimatedReadTime: "6 min",
    difficulty: "intermediate",
    role: "admin",
    relatedArticles: ["help-global-email-provider-setup", "help-global-microsoft-graph-connect"],
    lastUpdated: "2026-05-18",
    status: "published",
    featureReadiness: "Working",
  },

  // ── Global: Module switching ───────────────────────────────────────────────
  {
    id: "help-global-module-switching",
    title: "Switch Between CRM Modules",
    slug: "global-module-switching",
    crmScope: "global",
    category: "Getting Started",
    summary: "Use the TopBar module switcher to move between Donor CRM, Events CRM, and Compassion CRM.",
    body: "The module switcher is in the TopBar next to the platform name. Click it to see available modules: Donor CRM, Events CRM, Compassion CRM, and standalone apps. Data and navigation scope change to the selected module.",
    tags: ["global", "module-switcher", "navigation", "getting-started"],
    estimatedReadTime: "3 min",
    difficulty: "beginner",
    role: "all",
    relatedArticles: ["help-global-getting-started", "help-global-permissions"],
    lastUpdated: "2026-05-18",
    status: "published",
    featureReadiness: "Working",
  },
];
