<?php declare(strict_types=1); ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Form Letters | OyamaCRM</title><link rel="stylesheet" href="assets/app.css"></head><body>
<main class="shell"><header><div><p class="eyebrow">OyamaCRM · parallel workspace</p><h1>Form Letters</h1><p class="muted">A focused PHP workspace for donor letters and reviewable email drafts.</p></div><button id="logout" class="quiet" hidden>Sign out</button></header>
<section id="loginCard" class="card login"><h2>Connect to OyamaCRM</h2><p>Use your normal CRM account. Your access token stays in this PHP session and actions honor CRM permissions.</p><form id="loginForm"><label>Email<input id="email" type="email" required autocomplete="username"></label><label>Password<input id="password" type="password" required autocomplete="current-password"></label><button>Sign in</button></form></section>
<section id="workspace" hidden><div class="toolbar card"><label>Search donors<input id="search" placeholder="Name, email, or phone"></label><button id="findDonors">Find donors</button><span id="user" class="muted"></span></div><div class="layout"><section class="card donors"><div class="section-title"><h2>Recipients</h2><span id="recipientCount">0 selected</span></div><div id="donorResults" class="empty">Search donors to build a recipient list.</div></section><section class="card composer"><div class="section-title"><h2>Compose</h2><select id="mode"><option value="letter">Printable letter</option><option value="email">Email draft</option></select></div><label>Subject / letter title<input id="subject" value="Thank you for your support"></label><label>Message<textarea id="message" rows="12">Dear {{donor.firstName}},

Thank you for your generous support of {{organization.name}}. Your gift helps us continue this work.

With gratitude,
{{staff.name}}</textarea></label><div class="merge"><button type="button" data-token="{{donor.firstName}}">First name</button><button type="button" data-token="{{donor.fullName}}">Full name</button><button type="button" data-token="{{donor.address}}">Address</button><button type="button" data-token="{{organization.name}}">Organization</button></div><div class="actions"><button id="preview">Preview selected donor</button><button id="print" class="quiet">Print letter</button><button id="emailDraft" class="quiet">Create email draft</button></div><div class="generate"><label>CRM letter template<select id="letterTemplate"><option value="">Load active templates…</option></select></label><button id="generateLetters" class="quiet">Generate CRM letters</button></div></section></div><section class="card"><div class="section-title"><h2>Preview</h2><span id="status" class="muted" role="status"></span></div><article id="previewPaper" class="paper"><p>Select a donor and choose Preview selected donor.</p></article></section></section></main><script src="assets/app.js"></script></body></html>
