"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import WorkspaceBreadcrumbBar from "@/app/components/layout/WorkspaceBreadcrumbBar";
import { apiFetch } from "@/app/lib/auth-client";

type Confidence = "LOW" | "MEDIUM" | "HIGH";
type FindingStatus = "UNVERIFIED" | "VERIFIED" | "DISMISSED";
interface Constituent { id: string; firstName: string; lastName: string; displayName?: string | null; organizationName?: string | null; entityKind?: string | null; email?: string | null; city?: string | null; state?: string | null; employer?: string | null; donorStatus: string; totalLifetimeGiving?: string; }
interface Evidence { id?: string; provider: string; sourceRecordId: string; sourceUrl: string; signalType: string; title: string; subtitle?: string; summary: string; disclosedAmount?: number | string | null; disclosedAmountLabel?: string | null; sourcePublishedAt?: string | null; suggestedMatchConfidence?: "LOW"; suggestedMatchRationale?: string; matchConfidence?: Confidence; matchRationale?: string; status?: FindingStatus; facts?: Array<{ label: string; value: string }>; }
interface SourceRun { provider: string; name: string; status: "COMPLETED" | "SKIPPED" | "FAILED"; queries: string[]; resultCount: number; message: string; }
interface ProfileRecord { id: string; constituentId: string; generatedAt: string; status: "COMPLETE" | "PARTIAL"; sourceRuns: SourceRun[]; discoveredEvidence: Evidence[]; savedEvidence: Evidence[]; }

function nameOf(row: Constituent): string { return row.entityKind === "ORGANIZATION" ? row.organizationName || row.displayName || `${row.firstName} ${row.lastName}`.trim() : row.displayName || `${row.firstName} ${row.lastName}`.trim(); }
function money(value: string | number | null | undefined): string { const parsed = Number(value); return Number.isFinite(parsed) ? new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(parsed) : "—"; }

export default function AutomaticOyamaDonorProfileWorkspace({ initialConstituentId }: { initialConstituentId?: string }) {
  const [query, setQuery] = useState("");
  const [matches, setMatches] = useState<Constituent[]>([]);
  const [constituent, setConstituent] = useState<Constituent | null>(null);
  const [profile, setProfile] = useState<ProfileRecord | null>(null);
  const [findings, setFindings] = useState<Evidence[]>([]);
  const [reviewing, setReviewing] = useState<Evidence | null>(null);
  const [confidence, setConfidence] = useState<Confidence>("LOW");
  const [rationale, setRationale] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [notice, setNotice] = useState<string | null>(null);

  useEffect(() => {
    if (!initialConstituentId) return;
    void apiFetch<Constituent>(`/api/constituents/${encodeURIComponent(initialConstituentId)}`).then(async (row) => {
      setConstituent(row); setQuery(nameOf(row));
      const response = await apiFetch<{ findings: Evidence[] }>(`/api/donor-profile/findings?constituentId=${encodeURIComponent(row.id)}`);
      setFindings(response.findings);
    }).catch((requestError) => setError(requestError instanceof Error ? requestError.message : "Unable to load the selected constituent."));
  }, [initialConstituentId]);
  useEffect(() => {
    const value = query.trim();
    if (constituent && value === nameOf(constituent)) { setMatches([]); return; }
    if (value.length < 2) { setMatches([]); return; }
    const timer = window.setTimeout(() => { void apiFetch<Constituent[] | { items?: Constituent[] }>(`/api/constituents?search=${encodeURIComponent(value)}&limit=8`).then((response) => setMatches(Array.isArray(response) ? response : response.items ?? [])).catch((requestError) => setError(requestError instanceof Error ? requestError.message : "Constituent search failed.")); }, 250);
    return () => window.clearTimeout(timer);
  }, [query, constituent]);

  const counts = useMemo(() => ({ review: findings.filter((item) => item.status === "UNVERIFIED").length, verified: findings.filter((item) => item.status === "VERIFIED").length, discovered: profile?.discoveredEvidence.length ?? 0 }), [findings, profile]);
  async function loadFindings(id: string) { const response = await apiFetch<{ findings: Evidence[] }>(`/api/donor-profile/findings?constituentId=${encodeURIComponent(id)}`); setFindings(response.findings); }
  function selectConstituent(row: Constituent) { setConstituent(row); setQuery(nameOf(row)); setMatches([]); setProfile(null); setReviewing(null); setError(null); setNotice(null); void loadFindings(row.id).catch((requestError) => setError(requestError instanceof Error ? requestError.message : "Unable to load saved evidence.")); }
  async function researchProfile() {
    if (!constituent) { setError("Choose the constituent to research."); return; }
    setBusy(true); setError(null); setNotice(null); setReviewing(null);
    try { const response = await apiFetch<{ profile: ProfileRecord }>("/api/donor-profile/research", { method: "POST", body: JSON.stringify({ constituentId: constituent.id }) }); setProfile(response.profile); setFindings(response.profile.savedEvidence); setNotice(`OYAMADonorPROFILE returned ${response.profile.discoveredEvidence.length} discovered record${response.profile.discoveredEvidence.length === 1 ? "" : "s"} and ${response.profile.savedEvidence.length} saved evidence record${response.profile.savedEvidence.length === 1 ? "" : "s"}.`); }
    catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Unable to research this profile."); }
    finally { setBusy(false); }
  }
  function beginReview(result: Evidence) { setReviewing(result); setConfidence(result.suggestedMatchConfidence ?? "LOW"); setRationale(result.suggestedMatchRationale ?? ""); }
  async function saveEvidence() {
    if (!constituent || !reviewing) return;
    if (rationale.trim().length < 12) { setError("Explain why this public record may belong to the constituent."); return; }
    setBusy(true); setError(null);
    try { await apiFetch("/api/donor-profile/findings", { method: "POST", body: JSON.stringify({ constituentId: constituent.id, ...reviewing, matchConfidence: confidence, matchRationale: rationale.trim() }) }); await loadFindings(constituent.id); setReviewing(null); setNotice("Evidence saved as unverified for human review."); }
    catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Unable to save the evidence."); }
    finally { setBusy(false); }
  }
  async function reviewFinding(id: string, status: Exclude<FindingStatus, "UNVERIFIED">) { if (!constituent) return; try { await apiFetch(`/api/donor-profile/findings/${encodeURIComponent(id)}`, { method: "PATCH", body: JSON.stringify({ status }) }); await loadFindings(constituent.id); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Unable to review the evidence."); } }

  return <div className="mx-auto max-w-[1600px] space-y-4 py-3 sm:py-4">
    <WorkspaceBreadcrumbBar items={[{ label: "Steward Insights", href: "/steward" }, { label: "OYAMADonorPROFILE" }]} statusLabel="Automatic research" metadata="Evidence-first prospect record" accentTone="blue" />
    <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="bg-[linear-gradient(135deg,#f8fbff_0%,#edf6ff_55%,#ffffff_100%)] px-5 py-6 sm:px-7"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div className="max-w-4xl"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-blue-700">Oyama proprietary prospect intelligence</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-slate-950">OYAMADonorPROFILE</h1><p className="mt-2 text-sm leading-6 text-slate-600">Choose one constituent. OYAMA automatically searches every enabled source supported by that record and returns one source-attributed profile for review.</p></div><div className="grid grid-cols-3 gap-2 sm:min-w-[330px]"><Stat label="Discovered" value={counts.discovered} /><Stat label="Needs review" value={counts.review} /><Stat label="Verified" value={counts.verified} /></div></div></div><div className="grid gap-px border-t border-slate-200 bg-slate-200 lg:grid-cols-3"><Guardrail title="No source form" detail="Names, organizations, locations, employers, and known identifiers come from the selected CRM constituent." /><Guardrail title="No silent identity merge" detail="Unsupported sources are reported as skipped, and ambiguous records remain reviewable." /><Guardrail title="No net-worth claim" detail="Evidence and public indicators remain separate from estimated capacity and affinity." /></div></section>
    {error ? <p role="alert" className="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800">{error}</p> : null}{notice ? <p className="rounded-lg border border-blue-200 bg-blue-50 px-4 py-3 text-sm text-blue-900">{notice}</p> : null}
    <div className="grid gap-4 xl:grid-cols-[340px_minmax(0,1fr)]">
      <aside className="h-fit rounded-xl border border-slate-200 bg-white shadow-sm"><Heading step="1" title="Choose the constituent" detail="This is the only research input." /><div className="p-4"><label htmlFor="automatic-profile-person" className="text-xs font-semibold text-slate-700">Name, email, or organization</label><input id="automatic-profile-person" type="search" value={query} onChange={(event) => { setQuery(event.target.value); if (constituent && event.target.value !== nameOf(constituent)) setConstituent(null); }} placeholder="Search CRM records..." className="mt-1.5 w-full rounded-md border border-slate-300 px-3 py-2.5 text-sm" />{matches.length ? <div className="mt-2 divide-y divide-slate-100 overflow-hidden rounded-lg border border-slate-200">{matches.map((row) => <button key={row.id} type="button" onClick={() => selectConstituent(row)} className="block w-full px-3 py-2.5 text-left hover:bg-blue-50"><span className="block text-sm font-semibold text-slate-900">{nameOf(row)}</span><span className="block truncate text-xs text-slate-500">{[row.email, row.city, row.state].filter(Boolean).join(" · ")}</span></button>)}</div> : null}{constituent ? <div className="mt-4 rounded-lg border border-blue-200 bg-blue-50 p-3"><div className="flex justify-between gap-2"><div><p className="font-semibold text-blue-950">{nameOf(constituent)}</p><p className="text-xs text-blue-800">{[constituent.donorStatus, constituent.city, constituent.state].filter(Boolean).join(" · ")}</p></div><Link href={`/constituents/${encodeURIComponent(constituent.id)}`} className="text-xs font-semibold text-blue-700">CRM profile</Link></div><dl className="mt-3 grid grid-cols-2 gap-2 text-xs"><div><dt className="text-blue-700">Lifetime giving</dt><dd className="font-semibold text-blue-950">{money(constituent.totalLifetimeGiving)}</dd></div><div><dt className="text-blue-700">Employer</dt><dd className="truncate font-semibold text-blue-950">{constituent.employer || "Not recorded"}</dd></div></dl></div> : null}<button type="button" onClick={() => void researchProfile()} disabled={!constituent || busy} className="mt-4 w-full rounded-md bg-blue-700 px-4 py-3 text-sm font-semibold text-white hover:bg-blue-800 disabled:cursor-not-allowed disabled:opacity-50">{busy ? "Researching all sources…" : "Research this constituent"}</button><p className="mt-2 text-xs leading-5 text-slate-500">This sends server-selected public identifiers only to enabled, approved public-source connectors and records an audit event.</p></div></aside>
      <main className="space-y-4">
        <section className="rounded-xl border border-slate-200 bg-white shadow-sm"><Heading step="2" title="Returned OYAMADonorPROFILE record" detail="Every enabled source reports completed, skipped, or failed." /><div className="p-4">{!profile ? <p className="rounded-lg bg-slate-50 px-4 py-8 text-center text-sm text-slate-500">Choose a constituent and run automatic research to return the profile record.</p> : <><div className="flex flex-col gap-2 border-b border-slate-200 pb-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold text-slate-950">{profile.id}</p><p className="text-xs text-slate-500">Generated {new Date(profile.generatedAt).toLocaleString()}</p></div><span className={`w-fit rounded-full px-2.5 py-1 text-xs font-semibold ${profile.status === "COMPLETE" ? "bg-emerald-100 text-emerald-800" : "bg-amber-100 text-amber-800"}`}>{profile.status}</span></div><div className="mt-4 grid gap-3 lg:grid-cols-3">{profile.sourceRuns.map((run) => <article key={run.provider} className="rounded-lg border border-slate-200 p-3"><div className="flex items-start justify-between gap-2"><h3 className="text-sm font-semibold text-slate-950">{run.name}</h3><span className="text-[10px] font-semibold text-slate-500">{run.status}</span></div><p className="mt-2 text-2xl font-semibold tabular-nums text-slate-950">{run.resultCount}</p><p className="text-[10px] uppercase tracking-wide text-slate-500">records</p><p className="mt-2 text-xs leading-5 text-slate-600">{run.message}</p></article>)}</div><div className="mt-5 space-y-3"><h3 className="text-sm font-semibold text-slate-950">Discovered public records</h3>{!profile.discoveredEvidence.length ? <p className="rounded-lg bg-slate-50 px-3 py-5 text-sm text-slate-500">No new public records were returned by the currently enabled sources.</p> : profile.discoveredEvidence.map((item) => <EvidenceCard key={`${item.provider}-${item.sourceRecordId}`} item={item} action={<button type="button" onClick={() => beginReview(item)} className="rounded-md border border-blue-300 bg-blue-50 px-3 py-2 text-xs font-semibold text-blue-800">Review identity match</button>} />)}</div></>}</div></section>
        {reviewing ? <section className="rounded-xl border-2 border-amber-300 bg-amber-50 p-4"><p className="text-xs font-semibold uppercase text-amber-800">Human identity review required</p><h2 className="mt-1 font-semibold text-amber-950">{reviewing.title}</h2><div className="mt-3 grid gap-3 sm:grid-cols-[150px_minmax(0,1fr)]"><label className="text-xs font-semibold">Confidence<select value={confidence} onChange={(event) => setConfidence(event.target.value as Confidence)} className="mt-1 block w-full rounded-md border border-amber-300 bg-white px-3 py-2"><option>LOW</option><option>MEDIUM</option><option>HIGH</option></select></label><label className="text-xs font-semibold">Why this record may belong to the constituent<textarea value={rationale} onChange={(event) => setRationale(event.target.value)} rows={3} className="mt-1 block w-full rounded-md border border-amber-300 bg-white px-3 py-2" /></label></div><div className="mt-3 flex gap-2"><button type="button" onClick={() => void saveEvidence()} disabled={busy} className="rounded-md bg-amber-800 px-3 py-2 text-xs font-semibold text-white">Save as unverified</button><button type="button" onClick={() => setReviewing(null)} className="rounded-md border border-amber-300 bg-white px-3 py-2 text-xs font-semibold">Cancel</button></div></section> : null}
        <section className="rounded-xl border border-slate-200 bg-white shadow-sm"><Heading step="3" title="Saved evidence record" detail="Existing and newly reviewed records remain attached to this constituent." /><div className="space-y-3 p-4">{!findings.length ? <p className="rounded-lg bg-slate-50 px-3 py-5 text-sm text-slate-500">No saved public evidence yet.</p> : findings.map((item) => <EvidenceCard key={item.id} item={item} action={item.status === "UNVERIFIED" && item.id ? <div className="flex gap-2"><button type="button" onClick={() => void reviewFinding(item.id!, "VERIFIED")} className="rounded-md bg-emerald-700 px-2.5 py-1.5 text-xs font-semibold text-white">Verify</button><button type="button" onClick={() => void reviewFinding(item.id!, "DISMISSED")} className="rounded-md border border-slate-300 px-2.5 py-1.5 text-xs font-semibold">Dismiss</button></div> : null} />)}</div></section>
      </main>
    </div>
  </div>;
}

function Heading({ step, title, detail }: { step: string; title: string; detail: string }) { return <div className="border-b border-slate-200 px-4 py-3"><div className="flex items-start gap-3"><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-blue-700 text-xs font-bold text-white">{step}</span><div><h2 className="text-sm font-semibold text-slate-950">{title}</h2><p className="mt-0.5 text-xs text-slate-500">{detail}</p></div></div></div>; }
function Guardrail({ title, detail }: { title: string; detail: string }) { return <div className="bg-white px-5 py-4"><p className="text-xs font-semibold text-slate-900">{title}</p><p className="mt-1 text-xs leading-5 text-slate-600">{detail}</p></div>; }
function Stat({ label, value }: { label: string; value: number }) { return <div className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-center"><p className="text-lg font-semibold tabular-nums">{value}</p><p className="text-[10px] font-semibold uppercase text-slate-500">{label}</p></div>; }
function EvidenceCard({ item, action }: { item: Evidence; action: React.ReactNode }) { return <article className="rounded-lg border border-slate-200 p-3"><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><p className="font-semibold text-slate-950">{item.title}</p><p className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">{item.provider.replaceAll("_", " ")}{item.status ? ` · ${item.status}` : ""}</p></div><a href={item.sourceUrl} target="_blank" rel="noreferrer" className="text-xs font-semibold text-blue-700">Open original ↗</a></div><p className="mt-2 text-xs leading-5 text-slate-600">{item.summary}</p>{item.matchRationale ? <p className="mt-2 rounded-md bg-slate-50 px-2.5 py-2 text-xs"><strong>Identity confidence:</strong> {item.matchConfidence}<br />{item.matchRationale}</p> : null}<div className="mt-3">{action}</div></article>; }

