import * as React from "react";

export type OyamaIconName =
  | "dashboard"
  | "dashboard-tile"
  | "search"
  | "search-tile"
  | "filter"
  | "filter-tile"
  | "sort"
  | "sort-tile"
  | "settings"
  | "settings-tile"
  | "help"
  | "help-tile"
  | "users"
  | "users-tile"
  | "security"
  | "security-tile"
  | "integrations"
  | "integrations-tile"
  | "billing"
  | "billing-tile"
  | "donors"
  | "donors-tile"
  | "contacts"
  | "contacts-tile"
  | "donation"
  | "donation-tile"
  | "campaign"
  | "campaign-tile"
  | "reports"
  | "reports-tile"
  | "analytics"
  | "analytics-tile"
  | "tasks"
  | "tasks-tile"
  | "notes"
  | "notes-tile"
  | "files"
  | "files-tile"
  | "chat"
  | "chat-tile"
  | "clients"
  | "clients-tile"
  | "calendar"
  | "calendar-tile"
  | "forms"
  | "forms-tile"
  | "appointments"
  | "appointments-tile"
  | "case-notes"
  | "case-notes-tile"
  | "resources"
  | "resources-tile"
  | "pregnancy-test"
  | "pregnancy-test-tile"
  | "ultrasound"
  | "ultrasound-tile"
  | "material-aid"
  | "material-aid-tile"
  | "referrals"
  | "referrals-tile"
  | "events"
  | "events-tile"
  | "tickets"
  | "tickets-tile"
  | "attendees"
  | "attendees-tile"
  | "sponsors"
  | "sponsors-tile"
  | "auction"
  | "auction-tile"
  | "table-seating"
  | "table-seating-tile"
  | "check-in"
  | "check-in-tile"
  | "fish-race"
  | "fish-race-tile"
  | "event-page"
  | "event-page-tile"
  | "event-analytics"
  | "event-analytics-tile"
  | "email"
  | "email-tile"
  | "letters"
  | "letters-tile"
  | "media"
  | "media-tile"
  | "newsletter"
  | "newsletter-tile"
  | "sms"
  | "sms-tile"
  | "templates"
  | "templates-tile"
  | "inbox"
  | "inbox-tile"
  | "send"
  | "send-tile"
  | "draft"
  | "draft-tile"
  | "sequence"
  | "sequence-tile"
  | "steward-paths"
  | "steward-paths-tile"
  | "path-library"
  | "path-library-tile"
  | "builder"
  | "builder-tile"
  | "enrollments"
  | "enrollments-tile"
  | "activity"
  | "activity-tile"
  | "automation"
  | "automation-tile"
  | "trigger"
  | "trigger-tile"
  | "branch"
  | "branch-tile"
  | "delay"
  | "delay-tile"
  | "exit-goal"
  | "exit-goal-tile"
  | "validation"
  | "validation-tile"
  | "publish"
  | "publish-tile"
  | "archive"
  | "archive-tile"
  | "import"
  | "import-tile"
  | "export"
  | "export-tile"
  | "template"
  | "template-tile"
  | "first-time-donor"
  | "first-time-donor-tile"
  | "lapsed-donor"
  | "lapsed-donor-tile"
  | "major-gift"
  | "major-gift-tile"
  | "monthly-donor"
  | "monthly-donor-tile"
  | "gift-received"
  | "gift-received-tile"
  | "event-attended"
  | "event-attended-tile"
  | "send-email"
  | "send-email-tile"
  | "generate-letter"
  | "generate-letter-tile"
  | "create-task"
  | "create-task-tile"
  | "update-donor"
  | "update-donor-tile"
  | "add-tag"
  | "add-tag-tile"
  | "remove-tag"
  | "remove-tag-tile"
  | "notify-staff"
  | "notify-staff-tile"
  | "assign-owner"
  | "assign-owner-tile"
  | "create-note"
  | "create-note-tile"
  | "call-reminder"
  | "call-reminder-tile"
  | "segment"
  | "segment-tile"
  | "condition-check"
  | "condition-check-tile"
  | "split-path"
  | "split-path-tile"
  | "merge-path"
  | "merge-path-tile"
  | "limit-frequency"
  | "limit-frequency-tile"
  | "mark-complete"
  | "mark-complete-tile"
  | "steward-paths-special"
  | "steward-paths-special-16"
  | "steward-paths-special-24"
  | "steward-paths-special-32"
  | "steward-paths-special-48"
  | "steward-paths-special-64"
  | "steward-paths-special-128"
  | "steward-paths-special-256";

export type OyamaIconProps = React.SVGProps<SVGSVGElement> & {
  name: OyamaIconName;
  size?: number;
  title?: string;
};

/**
 * Uses /sprite/oyama-icons-sprite.svg from this icon pack.
 * Copy sprite into your public folder, then render:
 * <OyamaIcon name="steward-paths-special" size={32} />
 */
export function OyamaIcon({ name, size = 24, title, ...props }: OyamaIconProps) {
  const viewBox = name === "steward-paths-special" ? "0 0 512 512" : "0 0 48 48";
  return (
    <svg width={size} height={size} viewBox={viewBox} role={title ? "img" : "presentation"} aria-hidden={title ? undefined : true} {...props}>
      {title ? <title>{title}</title> : null}
      <use href={`/sprite/oyama-icons-sprite.svg#oyama-${name}`} />
    </svg>
  );
}
